// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "SecretaryKit",
    platforms: [.iOS(.v17)],
    products: [
        .library(name: "SecretaryKit", targets: ["SecretaryKit"]),
    ],
    targets: [
        // The XCFramework built by ios/scripts/build-xcframework.sh.
        .binaryTarget(name: "SecretaryFFI", path: "../Secretary.xcframework"),
        // High-level Swift API generated by uniffi-bindgen (secretary.swift),
        // which imports the low-level Clang module vended by the XCFramework.
        .target(name: "SecretaryKit", dependencies: ["SecretaryFFI"]),
        // Linked-call proof: opens golden_vault_001 on the simulator.
        .testTarget(
            name: "SecretaryKitTests",
            dependencies: ["SecretaryKit"],
            resources: [
                .copy("Resources/golden_vault_001"),
                .copy("Resources/golden_vault_001_inputs.json"),
            ]
        ),
    ]
)
