#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
secretary spec-doc test-name freshness check.

Run with (PEP 723; uv resolves Python; no external deps):

    uv run core/tests/python/spec_test_name_freshness.py

Detects drift between docs/*.md test-name citations and the actual Rust
code under `core/`. Surfaced after the 2026-05-02 §5 verification-trace
audit found 4 stale citations + ~20 missing entries in
docs/threat-model.md; mechanising the check turns periodic-audit pain
into immediate-CI feedback on a code rename.

Modes:
    (default)             scan + resolve, exit 0/1 on result
    --list-files          print the resolved doc set and exit
    --self-test           run the in-script smoke fixture and exit
    --audit-allowlist     also flag allowlist entries that now resolve
    --verbose             include resolved citations in human output
    --quiet               print only PASS / FAIL line (CI use)

Suggested CI invocation (no workflow file shipped — separate decision):

    uv run core/tests/python/spec_test_name_freshness.py --self-test \\
        && uv run core/tests/python/spec_test_name_freshness.py --quiet

Exit codes (mirrors core/tests/python/conformance.py):
    0  - all citations resolve or are allowlisted; no stale allowlist
    1  - drift detected (unresolved or stale-allowlist)
    2  - scan setup failure (missing input, malformed allowlist, etc.)
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Literal

# ---------------------------------------------------------------------------
# Project layout
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[3]
DOCS_ROOT = REPO_ROOT / "docs"
CORE_ROOT = REPO_ROOT / "core"
ALLOWLIST_PATH = REPO_ROOT / "core" / "tests" / "python" / "spec_freshness_allowlist.txt"

# Default scan set: high + medium signal docs that cite real Rust identifiers.
# Excluded by default: docs/TODO_*.md (historical), docs/manual/hardening-security.md +
# docs/manual/primer/cryptography/* (tutorial prose), docs/superpowers/{plans,specs}/*
# (frozen plan/spec docs), top-level README/ROADMAP/CLAUDE/secretary_next_session.
DEFAULT_DOC_GLOBS: tuple[str, ...] = (
    "crypto-design.md",
    "vault-format.md",
    "threat-model.md",
    "glossary.md",
    "manual/contributors/*.md",
    "adr/*.md",
)

# PATH_BARE recognition is enabled only for docs that densely cite tests
# (threat-model.md §5 verification trace; the contributor audit memos).
# Other docs (crypto-design.md, vault-format.md, glossary.md, ADRs) cite
# wire-format and CBOR field names that look like Rust fn names but aren't —
# enabling PATH_BARE there yields ~100 false positives per run. Docs not in
# this set still get RICH / BRACE / CONTINUATION / QUALIFIED checking.
BARE_EAGER_DOC_PATTERNS: tuple[str, ...] = (
    "threat-model.md",
    "manual/contributors/*.md",
)


def _is_bare_eager_doc(doc_path: Path, docs_root: Path) -> bool:
    try:
        rel = doc_path.relative_to(docs_root)
    except ValueError:
        return False
    rel_posix = rel.as_posix()
    for pattern in BARE_EAGER_DOC_PATTERNS:
        if Path(rel_posix).match(pattern):
            return True
    return False


# Standard library / derived trait methods that won't appear as literal
# tokens in the implementing type's file (typically generated by `#[derive(...)]`
# or implemented at the trait, not the impl, site). When a QUALIFIED citation
# references one of these, we accept it as long as the type itself is known.
DERIVED_TRAIT_METHODS: frozenset[str] = frozenset(
    {
        "Drop",
        "Clone",
        "Copy",
        "Debug",
        "Display",
        "PartialEq",
        "Eq",
        "Hash",
        "Default",
        "Iterator",
        "Send",
        "Sync",
        "Zeroize",
        "ZeroizeOnDrop",
        "Serialize",
        "Deserialize",
    }
)


# ---------------------------------------------------------------------------
# Citation extraction (pure)
# ---------------------------------------------------------------------------

CitationKind = Literal["RICH", "BRACE", "CONTINUATION", "QUALIFIED", "PATH_BARE"]


@dataclass(frozen=True)
class Citation:
    """One extracted backtick span, classified for resolution.

    `name` semantics by kind:
      RICH         - bare fn name (`path_hint` carries the .rs file).
      BRACE        - never directly emitted; expanded to per-element citations
                     (each becoming RICH if the brace prefix had a path or
                     PATH_BARE otherwise) before downstream resolution.
      CONTINUATION - the `_suffix_with_underscores` part; resolution must
                     pair it with the most recent non-CONTINUATION citation
                     on the same line (the "anchor") via a strip-N search.
      QUALIFIED    - the variant/const name (`path_hint` carries the type).
      PATH_BARE    - the bare snake_case name.
    """

    doc_path: Path
    line_no: int
    raw_span: str
    kind: CitationKind
    name: str
    path_hint: str | None  # for RICH: rust file; QUALIFIED: type; CONTINUATION: anchor.name; else None
    anchor_file: str | None = None  # for CONTINUATION: anchor.path_hint when anchor was RICH


# Spans containing any of these characters are treated as descriptive prose,
# not identifier candidates. Filters out command lines, formulas, paths-as-prose.
_SPAN_REJECT_CHARS = frozenset(" \t()=<>→‖*?'\"\\|→")

# Builtin denylist — a span entering here is genuinely never a Rust test/fn name
# in this repo. Per-doc one-off exceptions belong in the allowlist file, not
# here. Append-only: only add when a new false positive is observed *and* the
# term truly has no Rust-fn meaning.
DENYLIST: frozenset[str] = frozenset(
    {
        # File / config tokens (recognised as backticked identifiers but never fns)
        "Cargo.toml",
        "vault.toml",
        "rust-toolchain.toml",
        "manifest.cbor.enc",
        "identity.bundle.enc",
        # Tool / external-crate names
        "cargo",
        "cargo-fuzz",
        "clippy",
        "rustup",
        "uv",
        "zeroize",
        "getrandom",
        "tempfile",
        "pyo3",
        "uniffi",
        "blake3",
        "cbor2",
        "mnemonic",
        "secrecy",
        # Generic spec / CBOR / wire-format field names (look like fns, aren't)
        "vault_uuid",
        "format_version",
        "suite_id",
        "tombstoned_at_ms",
        "last_mod_ms",
        "kdf_params",
        "unknown",
        "unknown_hex",
        "fingerprint",
        "block_uuid",
        "device_uuid",
        "display_name",
        "author_fingerprint",
        # Fuzz target basenames (live under core/fuzz/, excluded from workspace)
        "vault_toml",
        "contact_card",
        "bundle_file",
        "manifest_file",
        "block_file",
        # JSON / cross-language protocol field names
        "reencoded_b64",
        "error_class",
        "must_not_panic",
        # Spec role / KDF role names
        "wrap_pw",
        "wrap_recovery",
        # Python conformance helpers (live in core/tests/python/conformance.py, not Rust)
        "py_decode",
        "py_encode",
        "py_merge_record",
        "py_merge_unknown_map",
        "run_diff_replay",
        # Local Rust variable names cited verbatim in audit memos (not fn names)
        "ed_sk_bytes",
        "x_sk_bytes",
        "bck_key_bytes",
        "ss_x_bytes",
        "ss_pq_bytes",
        # External RustCrypto / curve25519-dalek upstream APIs cited as references
        "fill_bytes",
        "diffie_hellman",
        "extract_and_expand",
    }
)


# Regexes for the five recognisers. Order matters in classify_span.
_RE_RICH = re.compile(
    r"^(core/[A-Za-z0-9_/\-.]+\.rs)::([A-Za-z_][A-Za-z0-9_]*)$"
)
# BRACE: optional path prefix (`core/...rs::`), then a snake_case prefix,
# then `_{a,b,c}`, then optional snake_case suffix.
_RE_BRACE = re.compile(
    r"^(?:(core/[A-Za-z0-9_/\-.]+\.rs)::)?"  # optional file
    r"([A-Za-z_][A-Za-z0-9_]*)"  # prefix
    r"_\{([a-z0-9_,]+)\}"  # _{a,b,c}
    r"(_[a-z0-9_]+)?$"  # optional trailing _suffix
)
_RE_CONTINUATION = re.compile(r"^_[a-z][a-z0-9_]*$")
_RE_QUALIFIED = re.compile(
    r"^([A-Z][A-Za-z0-9]*)::([A-Z][A-Za-z0-9_]*)$"
)
_RE_PATH_BARE = re.compile(r"^[a-z_][a-z0-9_]*$")


def strip_fenced_blocks(text: str) -> str:
    """Remove ``` ... ``` fenced blocks (and ~~~ variants).

    Leaves inline backticks alone. State machine on lines: a line whose
    *stripped* form starts with ``` or ~~~ toggles 'inside fence'.
    """
    out: list[str] = []
    in_fence = False
    for line in text.splitlines(keepends=True):
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            # Replace the fence line itself with a blank line so line numbers
            # in the surviving text match the source.
            out.append("\n" if line.endswith("\n") else "")
            continue
        if in_fence:
            out.append("\n" if line.endswith("\n") else "")
        else:
            out.append(line)
    return "".join(out)


_RE_LINK = re.compile(r"\[([^\]\n]*)\]\([^)\n]*\)")
_RE_BACKTICK_SPAN = re.compile(r"`([^`\n]+)`")


def extract_inline_backtick_spans(text: str) -> list[tuple[int, str]]:
    """Return (line_no, span) for every inline-backtick span.

    Markdown-link syntax `[label](target)` is collapsed to `label` first, so
    backticks inside the label are still captured but URL targets aren't
    mined for false positives.
    """
    flat = strip_fenced_blocks(text)
    flat = _RE_LINK.sub(r"\1", flat)

    out: list[tuple[int, str]] = []
    for line_no, line in enumerate(flat.splitlines(), start=1):
        for match in _RE_BACKTICK_SPAN.finditer(line):
            out.append((line_no, match.group(1)))
    return out


def _looks_like_prose(span: str) -> bool:
    return any(ch in _SPAN_REJECT_CHARS for ch in span)


def classify_span(
    span: str,
    *,
    doc_path: Path,
    line_no: int,
    denylist: frozenset[str] = DENYLIST,
    bare_eager: bool = True,
) -> Citation | None:
    """Map one backtick span to a Citation, or None if it isn't an identifier candidate.

    Returns None for prose spans, denylisted tokens, and bare names too short
    or too generic to be plausible test names. Order matters: RICH and BRACE
    are tried before CONTINUATION/QUALIFIED/PATH_BARE so a span matching both
    falls into the more-specific bucket.

    `bare_eager` controls whether PATH_BARE classification fires for this doc.
    Spec docs (crypto-design.md, vault-format.md, glossary.md) cite wire-format
    field names that look like Rust fn names but aren't — passing False there
    suppresses the noise. RICH / BRACE / CONTINUATION / QUALIFIED still fire.
    """
    if not span or _looks_like_prose(span):
        return None
    if span in denylist:
        return None

    if m := _RE_RICH.match(span):
        return Citation(doc_path, line_no, span, "RICH", m.group(2), m.group(1))

    if m := _RE_BRACE.match(span):
        # Brace citations are placeholders; expand_brace yields the actual
        # candidates that downstream resolution sees.
        return Citation(
            doc_path,
            line_no,
            span,
            "BRACE",
            m.group(2),  # prefix
            m.group(1),  # path (or None)
        )

    if _RE_CONTINUATION.match(span):
        return Citation(doc_path, line_no, span, "CONTINUATION", span, None)

    if m := _RE_QUALIFIED.match(span):
        return Citation(doc_path, line_no, span, "QUALIFIED", m.group(2), m.group(1))

    if bare_eager and _RE_PATH_BARE.match(span):
        # Cut bare-name noise: require ≥ 6 chars AND at least one underscore.
        if len(span) < 6 or "_" not in span:
            return None
        return Citation(doc_path, line_no, span, "PATH_BARE", span, None)

    return None


def expand_brace(citation: Citation) -> list[Citation]:
    """Expand a BRACE citation into N per-element citations.

    `prefix_{a,b,c}_suffix` → [`prefix_a_suffix`, `prefix_b_suffix`, `prefix_c_suffix`].
    Each expansion becomes RICH (if the original had a path prefix) or PATH_BARE.
    Non-BRACE inputs are returned unchanged in a single-element list.
    """
    if citation.kind != "BRACE":
        return [citation]
    m = _RE_BRACE.match(citation.raw_span)
    if not m:
        return []
    file_path, prefix, csv, trailing = m.group(1), m.group(2), m.group(3), m.group(4) or ""
    parts = [p.strip() for p in csv.split(",") if p.strip()]
    out: list[Citation] = []
    for part in parts:
        name = f"{prefix}_{part}{trailing}"
        out.append(
            Citation(
                citation.doc_path,
                citation.line_no,
                f"{citation.raw_span}→{name}",
                "RICH" if file_path else "PATH_BARE",
                name,
                file_path,
            )
        )
    return out


def attach_continuation_anchors(citations: Iterable[Citation]) -> list[Citation]:
    """For each CONTINUATION, fill in `path_hint`/`anchor_file` from the most
    recent non-CONTINUATION citation on the SAME line (and same doc).

    Continuations whose anchor cannot be determined (e.g. they appear before
    any anchor on the line) are left with path_hint=None; resolution will
    flag them as `CONTINUATION-UNRESOLVED` later.
    """
    out: list[Citation] = []
    last_anchor: Citation | None = None
    last_anchor_key: tuple[Path, int] | None = None
    for c in citations:
        if c.kind != "CONTINUATION":
            out.append(c)
            if c.kind != "BRACE":  # BRACE is a placeholder; not a useful anchor
                last_anchor = c
                last_anchor_key = (c.doc_path, c.line_no)
            continue
        if last_anchor is not None and last_anchor_key == (c.doc_path, c.line_no):
            out.append(
                Citation(
                    c.doc_path,
                    c.line_no,
                    c.raw_span,
                    "CONTINUATION",
                    c.name,
                    last_anchor.name,
                    last_anchor.path_hint if last_anchor.kind == "RICH" else None,
                )
            )
        else:
            # Orphan continuation; preserve as-is so resolution can flag it.
            out.append(c)
    return out


# ---------------------------------------------------------------------------
# Rust source indexers (I/O)
# ---------------------------------------------------------------------------

# Match `fn name(`, allowing visibility / async / const / unsafe modifiers.
# Anchored at line start (with optional whitespace) so we skip references
# inside comments/strings the vast majority of the time.
_RE_RUST_FN = re.compile(
    r"^\s*(?:pub(?:\s*\([^)]+\))?\s+)?(?:async\s+)?(?:const\s+)?(?:unsafe\s+)?"
    r"fn\s+([A-Za-z_][A-Za-z0-9_]*)"
)
# Match `enum Name`, `struct Name`, `trait Name` — capturing the type name.
_RE_RUST_TYPE = re.compile(
    r"^\s*(?:pub(?:\s*\([^)]+\))?\s+)?(?:enum|struct|trait)\s+([A-Za-z_][A-Za-z0-9_]*)"
)
# Match `const NAME: T = …` and `static NAME: T = …`.
_RE_RUST_CONST = re.compile(
    r"^\s*(?:pub(?:\s*\([^)]+\))?\s+)?(?:const|static)\s+([A-Z_][A-Z0-9_]*)\s*[:=]"
)


def _walk_rust_files(core_root: Path) -> list[Path]:
    """Enumerate `.rs` files under core/src and core/tests (excluding fuzz)."""
    out: list[Path] = []
    for sub in ("src", "tests"):
        root = core_root / sub
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*.rs")):
            out.append(path)
    return out


def _index_with_rg(core_root: Path, rg_pattern: str) -> dict[str, list[Path]] | None:
    """Run ripgrep against core/src and core/tests; return None if rg missing or fails."""
    rg = shutil.which("rg")
    if rg is None:
        return None
    cmd = [
        rg,
        "--type", "rust",
        "--no-heading",
        "--with-filename",
        "--line-number",
        "--only-matching",
        "--replace", "$1",
        "--multiline-dotall",  # tolerate macro spans; harmless for our regexes
        rg_pattern,
        str(core_root / "src"),
        str(core_root / "tests"),
    ]
    try:
        proc = subprocess.run(
            cmd,
            check=False,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    # rg exits 1 when no matches; treat both 0 and 1 as success, anything else as fallback.
    if proc.returncode not in (0, 1):
        return None
    out: dict[str, list[Path]] = defaultdict(list)
    for line in proc.stdout.splitlines():
        # Format: <file>:<line>:<captured>
        parts = line.split(":", 2)
        if len(parts) != 3:
            continue
        file_str, _, captured = parts
        out[captured].append(Path(file_str))
    return dict(out)


def _index_with_python(core_root: Path, regex: re.Pattern[str]) -> dict[str, list[Path]]:
    """Stdlib fallback: walk every .rs file and apply `regex` line by line."""
    out: dict[str, list[Path]] = defaultdict(list)
    for path in _walk_rust_files(core_root):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for line in text.splitlines():
            if m := regex.match(line):
                out[m.group(1)].append(path)
    return dict(out)


def build_rust_fn_index(core_root: Path) -> dict[str, list[Path]]:
    """Map every `fn name` declared under core/src + core/tests to the file(s) it lives in."""
    rg_pattern = (
        r"^\s*(?:pub(?:\s*\([^)]+\))?\s+)?(?:async\s+)?(?:const\s+)?(?:unsafe\s+)?"
        r"fn\s+([A-Za-z_][A-Za-z0-9_]*)"
    )
    if (idx := _index_with_rg(core_root, rg_pattern)) is not None:
        return idx
    return _index_with_python(core_root, _RE_RUST_FN)


def build_rust_type_index(core_root: Path) -> dict[str, list[Path]]:
    """Map every `enum/struct/trait/const/static NAME` to the file(s) it lives in.

    Used for QUALIFIED-citation resolution (`Type::Variant`, `Type::CONST`).
    Two regex passes — one for type defs, one for consts/statics — merged.
    """
    type_pattern = (
        r"^\s*(?:pub(?:\s*\([^)]+\))?\s+)?(?:enum|struct|trait)\s+([A-Za-z_][A-Za-z0-9_]*)"
    )
    const_pattern = (
        r"^\s*(?:pub(?:\s*\([^)]+\))?\s+)?(?:const|static)\s+([A-Z_][A-Z0-9_]*)\s*[:=]"
    )
    out: dict[str, list[Path]] = defaultdict(list)
    for pattern, py_re in (
        (type_pattern, _RE_RUST_TYPE),
        (const_pattern, _RE_RUST_CONST),
    ):
        idx = _index_with_rg(core_root, pattern)
        if idx is None:
            idx = _index_with_python(core_root, py_re)
        for name, paths in idx.items():
            out[name].extend(paths)
    # De-dup paths per name.
    return {name: list(dict.fromkeys(paths)) for name, paths in out.items()}


# ---------------------------------------------------------------------------
# Doc collection (I/O)
# ---------------------------------------------------------------------------


def collect_doc_files(
    docs_root: Path,
    *,
    default_globs: tuple[str, ...] = DEFAULT_DOC_GLOBS,
    includes: list[str] | None = None,
    excludes: list[str] | None = None,
) -> list[Path]:
    """Resolve the doc set to scan.

    `includes` (if non-empty) replaces the default glob set entirely.
    `excludes` is applied last and removes any matching path.
    All globs are interpreted relative to `docs_root`.
    """
    seen: set[Path] = set()
    ordered: list[Path] = []
    glob_set = tuple(includes) if includes else default_globs

    for pattern in glob_set:
        for path in sorted(docs_root.glob(pattern)):
            if path.is_file() and path not in seen:
                seen.add(path)
                ordered.append(path)

    if excludes:
        excluded: set[Path] = set()
        for pattern in excludes:
            for path in docs_root.glob(pattern):
                excluded.add(path.resolve())
        ordered = [p for p in ordered if p.resolve() not in excluded]

    return ordered


# ---------------------------------------------------------------------------
# Resolution
# ---------------------------------------------------------------------------

ResolutionStatus = Literal[
    "RESOLVED",
    "RICH-MISMATCH",
    "RICH-FILE-MISSING",
    "BARE-UNRESOLVED",
    "CONTINUATION-UNRESOLVED",
    "QUALIFIED-UNRESOLVED",
]


@dataclass(frozen=True)
class ResolutionResult:
    citation: Citation
    status: ResolutionStatus
    detail: str  # human-readable reason or resolved-name


def _rich_path_in_index(name: str, cited_rel_path: str, fn_idx: dict[str, list[Path]]) -> bool:
    """True if `name` is in the fn index under a path matching `cited_rel_path` (relative to repo root)."""
    paths = fn_idx.get(name, [])
    for p in paths:
        try:
            rel = p.relative_to(REPO_ROOT)
        except ValueError:
            rel = p
        if str(rel) == cited_rel_path:
            return True
    return False


def _try_continuation_strip_search(
    anchor_name: str,
    suffix: str,
    fn_idx: dict[str, list[Path]],
    *,
    constrain_file: str | None = None,
) -> str | None:
    """Strip 1..N segments from `anchor_name`, append `suffix`, return first match.

    `suffix` includes its leading underscore. If `constrain_file` is set
    (RICH anchor), the candidate must additionally live in that file.
    """
    parts = anchor_name.split("_")
    # Strip 1 segment, then 2, …, leaving at least 1 segment of prefix.
    for strip in range(1, len(parts)):
        prefix_parts = parts[:-strip]
        if not prefix_parts:
            break
        candidate = "_".join(prefix_parts) + suffix
        if candidate not in fn_idx:
            continue
        if constrain_file is None:
            return candidate
        if _rich_path_in_index(candidate, constrain_file, fn_idx):
            return candidate
    return None


def _qualified_member_in_file(member: str, type_paths: list[Path]) -> bool:
    """Cheap check: does any file declaring the type contain the variant/const?

    Two acceptable forms in the file: `Member` as an enum-variant token (followed
    by `,`/whitespace/`{`/`(`) or `Member` as a const declaration. We grep
    each file's text for word-boundary occurrences of `member` outside comments;
    the false-positive rate here is the price of a cheap heuristic but is low
    in practice because variant/const names are CamelCase or SCREAMING_SNAKE.
    """
    if not type_paths:
        return False
    pat = re.compile(rf"\b{re.escape(member)}\b")
    for path in type_paths:
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if pat.search(text):
            return True
    return False


def resolve_citation(
    c: Citation,
    fn_idx: dict[str, list[Path]],
    type_idx: dict[str, list[Path]],
) -> ResolutionResult:
    """Decide whether `c` resolves against the Rust source, returning a typed status."""
    if c.kind == "RICH":
        cited_path = REPO_ROOT / (c.path_hint or "")
        if not cited_path.is_file():
            return ResolutionResult(c, "RICH-FILE-MISSING", f"cited file not on disk: {c.path_hint}")
        if c.name in fn_idx:
            if not _rich_path_in_index(c.name, c.path_hint or "", fn_idx):
                elsewhere = [
                    str(p.relative_to(REPO_ROOT)) for p in fn_idx[c.name][:3]
                ]
                return ResolutionResult(
                    c,
                    "RICH-MISMATCH",
                    f"`fn {c.name}` exists but not in cited file; found in: {', '.join(elsewhere)}",
                )
            return ResolutionResult(c, "RESOLVED", str(cited_path.relative_to(REPO_ROOT)))
        # Not a fn — accept if it's a const/type declared in the cited file
        # (`TARGETS` etc. live in type_idx because they match `const NAME:`).
        if c.name in type_idx and _rich_path_in_index(c.name, c.path_hint or "", type_idx):
            return ResolutionResult(c, "RESOLVED", str(cited_path.relative_to(REPO_ROOT)))
        return ResolutionResult(c, "RICH-MISMATCH", f"no `fn {c.name}` anywhere under core/")

    if c.kind == "PATH_BARE":
        if c.name in fn_idx:
            paths = fn_idx[c.name]
            return ResolutionResult(c, "RESOLVED", str(paths[0].relative_to(REPO_ROOT)))
        return ResolutionResult(c, "BARE-UNRESOLVED", f"no `fn {c.name}` anywhere under core/")

    if c.kind == "CONTINUATION":
        anchor_name = c.path_hint
        if not anchor_name:
            return ResolutionResult(
                c,
                "CONTINUATION-UNRESOLVED",
                "no anchor citation on same line",
            )
        match = _try_continuation_strip_search(
            anchor_name, c.name, fn_idx, constrain_file=c.anchor_file
        )
        if match is not None:
            return ResolutionResult(c, "RESOLVED", match)
        constraint = f" (constrained to {c.anchor_file})" if c.anchor_file else ""
        return ResolutionResult(
            c,
            "CONTINUATION-UNRESOLVED",
            f"no strip-N expansion of {anchor_name!r}+{c.name!r} matched fn index{constraint}",
        )

    if c.kind == "QUALIFIED":
        type_name = c.path_hint or ""
        type_paths = type_idx.get(type_name, [])
        if not type_paths:
            return ResolutionResult(
                c,
                "QUALIFIED-UNRESOLVED",
                f"type `{type_name}` not declared anywhere under core/",
            )
        # Standard / derived trait methods (Drop, Clone, Debug, ...) won't
        # appear as literal tokens in the impl file when they're synthesised
        # by `#[derive(...)]`. Accept on type-existence alone.
        if c.name in DERIVED_TRAIT_METHODS:
            return ResolutionResult(
                c,
                "RESOLVED",
                f"derived trait method on type in {type_paths[0].relative_to(REPO_ROOT)}",
            )
        if not _qualified_member_in_file(c.name, type_paths):
            files = ", ".join(str(p.relative_to(REPO_ROOT)) for p in type_paths[:3])
            return ResolutionResult(
                c,
                "QUALIFIED-UNRESOLVED",
                f"`{c.name}` not found in declaring file(s): {files}",
            )
        return ResolutionResult(
            c,
            "RESOLVED",
            str(type_paths[0].relative_to(REPO_ROOT)),
        )

    # BRACE should never reach resolution (expand_brace runs first); treat as unresolved.
    return ResolutionResult(c, "BARE-UNRESOLVED", f"unexpanded BRACE citation: {c.raw_span}")


# ---------------------------------------------------------------------------
# Allowlist
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class AllowlistEntry:
    """One per-citation exception. `key` matches `<doc-rel-path>::<raw_span>`.

    `line_no` is the source line in the allowlist file (for malformed-file
    error reporting). `reason` is the user-supplied justification from the
    `# reason:` line that must immediately precede each entry.
    """

    key: str
    reason: str
    source_line: int


class AllowlistMalformed(ValueError):
    """Raised by load_allowlist when the file format is violated."""

    def __init__(self, line_no: int, message: str):
        super().__init__(f"line {line_no}: {message}")
        self.line_no = line_no
        self.message = message


def load_allowlist(path: Path) -> list[AllowlistEntry]:
    """Parse the allowlist file. Empty / missing file → empty list.

    Format (line-by-line state machine):
        # reason: <single-line justification>
        <doc-rel-path>::<exact-backtick-span>

    A `# reason:` line MUST immediately precede each entry (blank lines and
    `#`-comment lines OK between entries). Any other arrangement → error.
    """
    if not path.exists():
        return []
    out: list[AllowlistEntry] = []
    pending_reason: str | None = None
    pending_reason_line: int = 0
    for raw_line_no, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped:
            if pending_reason is not None:
                raise AllowlistMalformed(
                    raw_line_no, "blank line between `# reason:` and entry"
                )
            continue
        if stripped.startswith("# reason:"):
            if pending_reason is not None:
                raise AllowlistMalformed(
                    raw_line_no, "two `# reason:` lines in a row without entry"
                )
            pending_reason = stripped[len("# reason:"):].strip()
            pending_reason_line = raw_line_no
            if not pending_reason:
                raise AllowlistMalformed(raw_line_no, "`# reason:` line is empty")
            continue
        if stripped.startswith("#"):
            if pending_reason is not None:
                raise AllowlistMalformed(
                    raw_line_no,
                    "comment line between `# reason:` and entry",
                )
            continue
        # Non-comment, non-blank → must be an entry, must have a pending reason.
        if pending_reason is None:
            raise AllowlistMalformed(
                raw_line_no, "entry without preceding `# reason:` line"
            )
        out.append(AllowlistEntry(key=stripped, reason=pending_reason, source_line=pending_reason_line))
        pending_reason = None
    if pending_reason is not None:
        raise AllowlistMalformed(
            pending_reason_line, "trailing `# reason:` line without entry"
        )
    return out


def _citation_key(c: Citation, repo_root: Path) -> str:
    try:
        rel = c.doc_path.relative_to(repo_root)
    except ValueError:
        rel = c.doc_path
    return f"{rel.as_posix()}::{c.raw_span}"


def filter_allowlisted(
    results: list[ResolutionResult],
    allowlist: list[AllowlistEntry],
    repo_root: Path,
) -> tuple[list[ResolutionResult], list[ResolutionResult]]:
    """Split (live, suppressed). Allowlist matches a result by `<doc>::<raw_span>`."""
    keys = {entry.key for entry in allowlist}
    live: list[ResolutionResult] = []
    suppressed: list[ResolutionResult] = []
    for r in results:
        if r.status == "RESOLVED":
            live.append(r)
            continue
        if _citation_key(r.citation, repo_root) in keys:
            suppressed.append(r)
        else:
            live.append(r)
    return live, suppressed


def audit_allowlist(
    allowlist: list[AllowlistEntry],
    pre: list[Citation],
    fn_idx: dict[str, list[Path]],
    type_idx: dict[str, list[Path]],
    repo_root: Path,
) -> list[AllowlistEntry]:
    """Return allowlist entries whose underlying citation now resolves.

    These are 'stale' — the underlying drift was fixed but the allowlist
    entry was left behind. Surfacing them keeps the allowlist self-cleaning.
    """
    # Build key → citation map for the current scan.
    by_key: dict[str, Citation] = {}
    for c in pre:
        by_key[_citation_key(c, repo_root)] = c
    # Brace-expanded children share the original raw_span via the `→` decoration,
    # so they don't appear here; the original BRACE citation is what's keyed.
    stale: list[AllowlistEntry] = []
    for entry in allowlist:
        c = by_key.get(entry.key)
        if c is None:
            continue
        # If the citation still exists, run resolution. Brace-expand if needed.
        candidates = expand_brace(c) if c.kind == "BRACE" else [c]
        if all(
            resolve_citation(child, fn_idx, type_idx).status == "RESOLVED"
            for child in candidates
        ):
            stale.append(entry)
    return stale


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def _kind_summary(citations: list[Citation], expansions: int) -> str:
    counts: dict[str, int] = defaultdict(int)
    for c in citations:
        counts[c.kind] += 1
    parts = []
    for kind in ("RICH", "BRACE", "CONTINUATION", "QUALIFIED", "PATH_BARE"):
        if counts.get(kind):
            label = kind
            if kind == "BRACE" and expansions:
                label = f"BRACE→{expansions}"
            parts.append(f"{counts[kind]} {label}")
    return ", ".join(parts)


def render_human(
    docs_scanned: int,
    pre_expansion: list[Citation],
    expansions: int,
    results: list[ResolutionResult],
    *,
    verbose: bool,
    quiet: bool,
    suppressed_count: int = 0,
    stale_allowlist: list[AllowlistEntry] | None = None,
) -> tuple[str, bool]:
    """Render the human report. Returns (text, all_resolved)."""
    lines: list[str] = []
    unresolved = [r for r in results if r.status != "RESOLVED"]
    resolved = [r for r in results if r.status == "RESOLVED"]
    stale_allowlist = stale_allowlist or []
    all_ok = not unresolved and not stale_allowlist

    if quiet:
        if all_ok:
            return ("PASS\n", True)
        parts = []
        if unresolved:
            parts.append(f"{len(unresolved)} unresolved citation(s)")
        if stale_allowlist:
            parts.append(f"{len(stale_allowlist)} stale allowlist entry/entries")
        return (f"FAIL: {'; '.join(parts)}\n", False)

    lines.append("--- Section 1: doc citation index ---")
    lines.append(
        f"scanned {docs_scanned} docs, extracted {len(pre_expansion)} citations ({_kind_summary(pre_expansion, expansions)})"
    )
    lines.append("")
    lines.append("--- Section 2: resolution ---")
    suffix = f" ({suppressed_count} suppressed by allowlist)" if suppressed_count else ""
    lines.append(f"{len(resolved)} resolved, {len(unresolved)} unresolved{suffix}")

    if unresolved:
        lines.append("")
        lines.append("--- Unresolved ---")
        # Group by doc, then by status.
        by_doc: dict[Path, list[ResolutionResult]] = defaultdict(list)
        for r in unresolved:
            by_doc[r.citation.doc_path].append(r)
        for doc_path in sorted(by_doc, key=lambda p: str(p)):
            try:
                rel = doc_path.relative_to(REPO_ROOT)
            except ValueError:
                rel = doc_path
            lines.append(str(rel))
            for r in sorted(by_doc[doc_path], key=lambda r: (r.status, r.citation.line_no)):
                lines.append(f"  L{r.citation.line_no} [{r.status}] `{r.citation.raw_span}`")
                lines.append(f"    {r.detail}")

    if verbose and resolved:
        lines.append("")
        lines.append("--- Resolved ---")
        for r in resolved:
            try:
                rel = r.citation.doc_path.relative_to(REPO_ROOT)
            except ValueError:
                rel = r.citation.doc_path
            lines.append(f"  {rel}:L{r.citation.line_no} `{r.citation.raw_span}` → {r.detail}")

    if stale_allowlist:
        lines.append("")
        lines.append("--- Stale allowlist entries (citation now resolves; remove from allowlist) ---")
        for entry in stale_allowlist:
            lines.append(f"  L{entry.source_line} {entry.key}")
            lines.append(f"    reason was: {entry.reason}")

    lines.append("")
    if all_ok:
        lines.append("PASS")
    else:
        parts = []
        if unresolved:
            parts.append(f"{len(unresolved)} unresolved citation(s)")
        if stale_allowlist:
            parts.append(f"{len(stale_allowlist)} stale allowlist entry/entries")
        lines.append(f"FAIL: {'; '.join(parts)}")
    return ("\n".join(lines) + "\n", all_ok)


# ---------------------------------------------------------------------------
# Scan orchestration
# ---------------------------------------------------------------------------


def scan_docs(
    docs: list[Path],
    *,
    docs_root: Path = DOCS_ROOT,
) -> tuple[list[Citation], list[Citation], int]:
    """Read each doc, extract + classify backtick spans, attach continuation anchors,
    expand braces.

    Returns (pre_expansion, post_expansion_for_resolution, brace_expansion_count).
    pre_expansion is used for the per-kind summary; post_expansion is what
    resolution iterates.
    """
    pre: list[Citation] = []
    for doc in docs:
        try:
            text = doc.read_text(encoding="utf-8")
        except OSError:
            continue
        spans = extract_inline_backtick_spans(text)
        bare_eager = _is_bare_eager_doc(doc, docs_root)
        for line_no, span in spans:
            c = classify_span(span, doc_path=doc, line_no=line_no, bare_eager=bare_eager)
            if c is not None:
                pre.append(c)
    pre = attach_continuation_anchors(pre)

    expanded: list[Citation] = []
    brace_expansions = 0
    for c in pre:
        if c.kind == "BRACE":
            children = expand_brace(c)
            brace_expansions += len(children)
            expanded.extend(children)
        else:
            expanded.append(c)
    return pre, expanded, brace_expansions


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------


def _self_test_extraction() -> list[str]:
    """Smoke-test the pure extraction layer. Returns failure messages (empty = pass)."""
    failures: list[str] = []
    fake = Path("docs/fake.md")

    # Fenced blocks must not contribute spans.
    fenced = "before\n```\n`should_be_ignored`\n```\nafter `included_name`\n"
    spans = extract_inline_backtick_spans(fenced)
    if any(span == "should_be_ignored" for _, span in spans):
        failures.append("fenced block contents leaked into extraction")
    if not any(span == "included_name" for _, span in spans):
        failures.append("post-fence backtick span not extracted")

    # Markdown link labels keep their backticks; targets are dropped.
    linked = "[`labelled_name`](https://example.com)\n"
    spans = extract_inline_backtick_spans(linked)
    if not any(span == "labelled_name" for _, span in spans):
        failures.append("link-label backtick span not extracted")

    cases: list[tuple[str, CitationKind | None, str | None]] = [
        # (span, expected kind or None for filtered, expected name field)
        ("core/tests/sig.rs::ml_dsa_65_nist_keygen_kat", "RICH", "ml_dsa_65_nist_keygen_kat"),
        ("merge_record", "PATH_BARE", "merge_record"),
        ("UnlockError::WeakKdfParams", "QUALIFIED", "WeakKdfParams"),
        ("_sigver_kat", "CONTINUATION", "_sigver_kat"),
        # Filtering rules
        ("max", None, None),  # too short
        ("zeroize", None, None),  # denylisted
        ("vault_uuid", None, None),  # denylisted
        ("cargo test --release", None, None),  # prose / spaces
        ("Argon2idParams::V1_DEFAULT", "QUALIFIED", "V1_DEFAULT"),
    ]
    for span, expected_kind, expected_name in cases:
        got = classify_span(span, doc_path=fake, line_no=1)
        if expected_kind is None:
            if got is not None:
                failures.append(f"expected {span!r} to be filtered, got {got.kind}")
        else:
            if got is None:
                failures.append(f"expected {span!r} to classify as {expected_kind}, got None")
            elif got.kind != expected_kind:
                failures.append(f"{span!r}: expected {expected_kind}, got {got.kind}")
            elif got.name != expected_name:
                failures.append(f"{span!r}: expected name={expected_name!r}, got {got.name!r}")

    # Brace expansion.
    brace = classify_span(
        "argon2id_params_try_new_v1_{accepts_floor,rejects_zero_iterations,rejects_zero_parallelism}",
        doc_path=fake,
        line_no=1,
    )
    if brace is None or brace.kind != "BRACE":
        failures.append("brace span did not classify as BRACE")
    else:
        expanded = expand_brace(brace)
        names = [c.name for c in expanded]
        expected = [
            "argon2id_params_try_new_v1_accepts_floor",
            "argon2id_params_try_new_v1_rejects_zero_iterations",
            "argon2id_params_try_new_v1_rejects_zero_parallelism",
        ]
        if names != expected:
            failures.append(f"brace expansion mismatch: got {names}")

    # Continuation anchor attachment.
    rich = Citation(fake, 5, "core/tests/sig.rs::ml_dsa_65_nist_keygen_kat", "RICH",
                    "ml_dsa_65_nist_keygen_kat", "core/tests/sig.rs")
    cont1 = Citation(fake, 5, "_sigver_kat", "CONTINUATION", "_sigver_kat", None)
    cont2 = Citation(fake, 5, "_siggen_kat", "CONTINUATION", "_siggen_kat", None)
    other_line = Citation(fake, 6, "_orphan_suffix", "CONTINUATION", "_orphan_suffix", None)
    attached = attach_continuation_anchors([rich, cont1, cont2, other_line])
    if attached[1].path_hint != "ml_dsa_65_nist_keygen_kat":
        failures.append("continuation #1 did not get anchor name")
    if attached[1].anchor_file != "core/tests/sig.rs":
        failures.append("continuation #1 did not get anchor file")
    if attached[2].path_hint != "ml_dsa_65_nist_keygen_kat":
        failures.append("continuation #2 did not get anchor name")
    if attached[3].path_hint is not None:
        failures.append("orphan continuation should have no anchor (different line)")

    return failures


def _self_test_indexers() -> list[str]:
    """Smoke-test the Rust indexers against a synthetic on-disk core/."""
    failures: list[str] = []
    rust_source = """\
pub fn alpha_helper(x: u32) -> u32 { x }
fn beta_internal() {}
pub(crate) async unsafe fn gamma_complex_modifiers() {}

pub struct UnlockBundle;
pub enum UnlockError { WeakKdfParams, BadInput }
trait Verifier {}

pub const V1_DEFAULT: usize = 256;
const V1_MIN_MEMORY_KIB: usize = 64 * 1024;
static SHARED_FLAG: bool = false;

#[test]
fn delta_test_lives_under_tests_subdir() {}
"""
    with tempfile.TemporaryDirectory() as td:
        core = Path(td) / "core"
        (core / "src").mkdir(parents=True)
        (core / "tests").mkdir(parents=True)
        (core / "src" / "lib.rs").write_text(rust_source, encoding="utf-8")
        (core / "tests" / "extra.rs").write_text(
            "fn epsilon_under_tests() {}\n", encoding="utf-8"
        )

        fn_idx = build_rust_fn_index(core)
        for name in (
            "alpha_helper",
            "beta_internal",
            "gamma_complex_modifiers",
            "delta_test_lives_under_tests_subdir",
            "epsilon_under_tests",
        ):
            if name not in fn_idx:
                failures.append(f"fn index missing {name!r}")
        if "WeakKdfParams" in fn_idx:
            failures.append("fn index leaked enum variant 'WeakKdfParams'")

        type_idx = build_rust_type_index(core)
        for name in ("UnlockBundle", "UnlockError", "Verifier", "V1_DEFAULT", "V1_MIN_MEMORY_KIB"):
            if name not in type_idx:
                failures.append(f"type index missing {name!r}")
        if "alpha_helper" in type_idx:
            failures.append("type index leaked fn name 'alpha_helper'")

    return failures


def _self_test_resolution() -> list[str]:
    """End-to-end: synthetic doc + synthetic Rust file → run scan + resolve.

    Plants citations of every supported kind plus one stale citation; asserts
    the resolver classifies each correctly.
    """
    failures: list[str] = []
    rust_source = """\
pub fn alpha_helper() {}
pub fn beta_helper() {}
pub fn gamma_a() {}
pub fn gamma_b() {}
pub fn gamma_c() {}
pub fn ml_dsa_65_nist_keygen_kat() {}
pub fn ml_dsa_65_nist_sigver_kat() {}

pub enum SampleErr { GoodVariant }
pub struct Sensitive;
pub const TARGETS: usize = 4;
"""
    doc_text = """\
prose with `cargo` (denylisted) and `max` (too short).

Test citations:
- RICH passes: `core/src/lib.rs::alpha_helper`.
- RICH-MISMATCH (file ok, name not in it): `core/src/lib.rs::not_actually_here`.
- RICH-FILE-MISSING: `core/tests/missing.rs::beta_helper`.
- BARE passes: `beta_helper`.
- BARE-UNRESOLVED: `nonexistent_helper_function`.
- BRACE expands to gamma_a, gamma_b, gamma_c: `gamma_{a,b,c}`.
- CONTINUATION resolves via strip-2: `core/src/lib.rs::ml_dsa_65_nist_keygen_kat`, `_sigver_kat`.
- QUALIFIED resolves: `SampleErr::GoodVariant`.
- QUALIFIED unresolved type: `MissingType::NoSuchVariant`.
- RICH-as-const resolves (TARGETS is const, not fn): `core/src/lib.rs::TARGETS`.
- QUALIFIED derived-trait-method resolves on type alone: `Sensitive::Drop`.

```
Inside fenced block, `should_be_ignored` MUST NOT contribute.
```
"""
    with tempfile.TemporaryDirectory() as td:
        tdroot = Path(td)
        core = tdroot / "core"
        (core / "src").mkdir(parents=True)
        (core / "tests").mkdir(parents=True)
        (core / "src" / "lib.rs").write_text(rust_source, encoding="utf-8")
        # Place the synthetic doc under a path that matches BARE_EAGER_DOC_PATTERNS
        # so PATH_BARE recognition fires; this gates two of the expectations
        # (BARE passes / BARE-UNRESOLVED) below.
        docs_root = tdroot / "docs"
        contrib = docs_root / "manual" / "contributors"
        contrib.mkdir(parents=True)
        doc = contrib / "fake.md"
        doc.write_text(doc_text, encoding="utf-8")

        # Build indexes against the synthetic core.
        fn_idx = build_rust_fn_index(core)
        type_idx = build_rust_type_index(core)

        # Patch REPO_ROOT for this run so RICH path resolution treats `core/...`
        # citations as relative to `tdroot/`. We rebind the module global; restore
        # afterwards so the rest of the self-test isn't perturbed.
        global REPO_ROOT
        original_repo_root = REPO_ROOT
        REPO_ROOT = tdroot
        try:
            pre, expanded, _ = scan_docs([doc], docs_root=docs_root)
            results = [resolve_citation(c, fn_idx, type_idx) for c in expanded]
        finally:
            REPO_ROOT = original_repo_root

        by_status: dict[str, list[str]] = defaultdict(list)
        for r in results:
            by_status[r.status].append(r.citation.raw_span)

        def expect(status: str, contains: str) -> None:
            if not any(contains in span for span in by_status.get(status, [])):
                failures.append(
                    f"expected {status} containing {contains!r}, got status map: "
                    f"{dict(by_status)}"
                )

        expect("RESOLVED", "alpha_helper")
        expect("RESOLVED", "beta_helper")
        expect("RESOLVED", "gamma_{a,b,c}→gamma_a")
        expect("RESOLVED", "gamma_{a,b,c}→gamma_b")
        expect("RESOLVED", "gamma_{a,b,c}→gamma_c")
        expect("RESOLVED", "ml_dsa_65_nist_keygen_kat")
        expect("RESOLVED", "_sigver_kat")
        expect("RESOLVED", "SampleErr::GoodVariant")
        expect("RESOLVED", "core/src/lib.rs::TARGETS")
        expect("RESOLVED", "Sensitive::Drop")
        expect("RICH-MISMATCH", "not_actually_here")
        expect("RICH-FILE-MISSING", "missing.rs::beta_helper")
        expect("BARE-UNRESOLVED", "nonexistent_helper_function")
        expect("QUALIFIED-UNRESOLVED", "MissingType::NoSuchVariant")

        # Verify a doc outside the bare-eager set drops PATH_BARE classifications.
        non_eager_doc = docs_root / "crypto-design.md"
        non_eager_doc.write_text("`alpha_helper` and `beta_helper`\n", encoding="utf-8")
        REPO_ROOT = tdroot
        try:
            pre2, _, _ = scan_docs([non_eager_doc], docs_root=docs_root)
        finally:
            REPO_ROOT = original_repo_root
        if any(c.kind == "PATH_BARE" for c in pre2):
            failures.append("PATH_BARE fired for a non-bare-eager doc (crypto-design.md)")

        for c in pre:
            if "should_be_ignored" in c.raw_span:
                failures.append("fenced-block span leaked into citations")

    return failures


def _self_test_allowlist() -> list[str]:
    """Smoke-test allowlist parsing + filter_allowlisted + audit_allowlist."""
    failures: list[str] = []

    valid = """\
# spec_freshness_allowlist test fixture

# reason: prose negation, not a continuation
docs/crypto-design.md::_conflicts

# reason: KAT vector key, not a Rust fn
docs/threat-model.md::concurrent_tombstone_wins_preserves_live_unknown
"""
    with tempfile.TemporaryDirectory() as td:
        good = Path(td) / "good.txt"
        good.write_text(valid, encoding="utf-8")
        entries = load_allowlist(good)
        if len(entries) != 2:
            failures.append(f"valid allowlist parsed {len(entries)} entries, expected 2")
        elif entries[0].key != "docs/crypto-design.md::_conflicts":
            failures.append(f"first entry key wrong: {entries[0].key!r}")
        elif entries[0].reason != "prose negation, not a continuation":
            failures.append(f"first entry reason wrong: {entries[0].reason!r}")

        # Missing-file → empty list (not error).
        missing = Path(td) / "missing.txt"
        if load_allowlist(missing) != []:
            failures.append("missing allowlist file should return [] not raise")

        # Bad: entry without reason
        bad = Path(td) / "bad.txt"
        bad.write_text("docs/foo.md::bar\n", encoding="utf-8")
        try:
            load_allowlist(bad)
        except AllowlistMalformed as e:
            if "without preceding `# reason:`" not in str(e):
                failures.append(f"bad-no-reason: wrong error: {e}")
        else:
            failures.append("bad-no-reason: expected AllowlistMalformed")

        # Bad: blank line between reason and entry
        bad2 = Path(td) / "bad2.txt"
        bad2.write_text("# reason: x\n\ndocs/foo.md::bar\n", encoding="utf-8")
        try:
            load_allowlist(bad2)
        except AllowlistMalformed as e:
            if "blank line" not in str(e):
                failures.append(f"bad-blank-between: wrong error: {e}")
        else:
            failures.append("bad-blank-between: expected AllowlistMalformed")

    # filter_allowlisted: a matching entry suppresses an unresolved result.
    fake_doc = Path("docs/foo.md")
    cit = Citation(fake_doc, 5, "_conflicts", "CONTINUATION", "_conflicts", None)
    res_unresolved = ResolutionResult(cit, "CONTINUATION-UNRESOLVED", "no anchor")
    res_resolved = ResolutionResult(
        Citation(fake_doc, 6, "merge_record", "PATH_BARE", "merge_record", None),
        "RESOLVED",
        "x",
    )
    entry = AllowlistEntry(key="docs/foo.md::_conflicts", reason="x", source_line=1)
    live, suppressed = filter_allowlisted(
        [res_unresolved, res_resolved], [entry], REPO_ROOT
    )
    # Note: filter_allowlisted compares against repo-relative path; fake_doc is
    # already "docs/foo.md", and Path.relative_to(REPO_ROOT) will fail since
    # fake_doc isn't under REPO_ROOT — _citation_key falls through to as-is.
    # Confirm the suppression took.
    if len(suppressed) != 1 or suppressed[0].citation.raw_span != "_conflicts":
        failures.append(f"filter_allowlisted: expected _conflicts suppressed, got {suppressed}")
    if len(live) != 1 or live[0].status != "RESOLVED":
        failures.append(f"filter_allowlisted: live should be 1 resolved, got {live}")

    return failures


def run_self_test() -> int:
    """Run the in-script smoke fixture. Returns 0 on PASS, 1 on FAIL."""
    sections: list[tuple[str, list[str]]] = [
        ("extraction", _self_test_extraction()),
        ("indexers", _self_test_indexers()),
        ("resolution", _self_test_resolution()),
        ("allowlist", _self_test_allowlist()),
    ]
    any_fail = False
    for name, failures in sections:
        if failures:
            any_fail = True
            print(f"--- self-test section: {name} ---")
            for msg in failures:
                print(f"  FAIL: {msg}")
        else:
            print(f"--- self-test section: {name} ---")
            print("  ok")
    if any_fail:
        print("FAIL: self-test", file=sys.stderr)
        return 1
    print("PASS")
    return 0


# ---------------------------------------------------------------------------
# CLI glue
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        allow_abbrev=False,
        description="Detect drift between docs/*.md test-name citations and core/ Rust code.",
    )
    parser.add_argument(
        "--include",
        action="append",
        default=[],
        metavar="GLOB",
        help="glob (relative to docs/) to add to scan set; repeatable; replaces defaults",
    )
    parser.add_argument(
        "--exclude",
        action="append",
        default=[],
        metavar="GLOB",
        help="glob (relative to docs/) to remove from scan set; repeatable",
    )
    parser.add_argument(
        "--list-files",
        action="store_true",
        help="print the resolved doc set and exit 0",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="run the in-script smoke fixture and exit",
    )
    parser.add_argument(
        "--audit-allowlist",
        action="store_true",
        help="also fail if any allowlist entry now resolves (i.e. is stale)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="include resolved citations in human output",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="print only PASS / FAIL line (CI use)",
    )
    return parser


def main() -> int:
    parser = _build_parser()
    args, _ = parser.parse_known_args()

    if args.self_test:
        return run_self_test()

    if not DOCS_ROOT.is_dir():
        print(f"MISSING: docs root {DOCS_ROOT}", file=sys.stderr)
        return 2
    if not CORE_ROOT.is_dir():
        print(f"MISSING: core root {CORE_ROOT}", file=sys.stderr)
        return 2

    docs = collect_doc_files(DOCS_ROOT, includes=args.include, excludes=args.exclude)

    if args.list_files:
        for path in docs:
            print(path.relative_to(REPO_ROOT))
        return 0

    try:
        allowlist = load_allowlist(ALLOWLIST_PATH)
    except AllowlistMalformed as e:
        print(f"MISSING: malformed allowlist near {e}", file=sys.stderr)
        return 2

    fn_idx = build_rust_fn_index(CORE_ROOT)
    type_idx = build_rust_type_index(CORE_ROOT)
    pre, expanded, brace_expansions = scan_docs(docs)
    raw_results = [resolve_citation(c, fn_idx, type_idx) for c in expanded]
    live_results, suppressed = filter_allowlisted(raw_results, allowlist, REPO_ROOT)

    stale: list[AllowlistEntry] = []
    if args.audit_allowlist:
        stale = audit_allowlist(allowlist, pre, fn_idx, type_idx, REPO_ROOT)

    text, all_ok = render_human(
        len(docs), pre, brace_expansions, live_results,
        verbose=args.verbose, quiet=args.quiet,
        suppressed_count=len(suppressed),
        stale_allowlist=stale,
    )
    sys.stdout.write(text)

    fail_reasons: list[str] = []
    if not all_ok:
        unresolved = [r for r in live_results if r.status != "RESOLVED"]
        fail_reasons.append(f"{len(unresolved)} unresolved citation(s)")
    if stale:
        fail_reasons.append(f"{len(stale)} stale allowlist entry/entries")
    if fail_reasons:
        print(f"FAIL: {'; '.join(fail_reasons)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
