//! uniffi bindings for secretary-core.
//!
//! The crate-level `#![allow(unsafe_code)]` is the minimal escape hatch
//! for `uniffi::include_scaffolding!()`, which expands to the generated
//! `secretary.uniffi.rs` file in `OUT_DIR` containing `unsafe extern "C"`
//! blocks (the FFI bridge to the C ABI is inherently unsafe). The
//! crate-local lint relaxation (workspace `forbid` → crate-local `deny`)
//! is required because `forbid` is non-overridable by inner `#[allow]`;
//! see Cargo.toml.
//!
//! The `#[allow]` is **crate-level** rather than item-level because the
//! `include_scaffolding!()` macro generates code at crate scope (the
//! generated file declares `extern "C"` symbols and free functions). A
//! narrower item-level `#[allow]` doesn't cover that expansion. The
//! tradeoff: a future contributor who adds a hand-rolled `unsafe` block
//! anywhere in this crate gets silence rather than a `deny` error. The
//! crate is intentionally tiny and reviewed; new `unsafe` blocks should
//! be challenged in code review.
//!
//! # Module layout
//!
//! - `errors` — `UnlockError`, `VaultError`, and the bridge-to-uniffi
//!   `From` conversions.
//! - `wrappers` — opaque-handle wrappers around bridge-crate handle
//!   types, grouped by domain (`wrappers::identity`,
//!   `wrappers::vault`, `wrappers::block`).
//! - `namespace` — the namespace functions declared in `secretary.udl`
//!   (open, create, read_block, ...).
//!
//! Everything declared in those modules is `pub use`d at crate root so
//! uniffi's generated scaffolding (which references types via
//! `crate::TypeName` paths derived from the UDL) can find them.
//!
//! Rationale: secretary_next_session.md "Begin Sub-project B.1.1".
//!
//! B.3a adds the `open_with_recovery` namespace function and 2 new
//! `UnlockError` variants (`WrongMnemonicOrCorrupt`,
//! `InvalidMnemonic { detail }`).
//!
//! Rationale (B.3a): docs/superpowers/specs/2026-05-04-ffi-b3a-recovery-unlock-design.md
//!
//! B.3b adds the `create_vault` namespace function and 2 new opaque-
//! handle types (`CreateVaultOutput` dictionary, `MnemonicOutput`
//! interface).
//!
//! Rationale (B.3b): docs/superpowers/specs/2026-05-05-ffi-b3b-create-vault-design.md
//!
//! B.4a/B.4b add folder-based open and per-block read paths, with the
//! 7-variant `VaultError` mirroring `FfiVaultError` plus the uniffi-only
//! `InvalidArgument` 8th variant.

#![allow(unsafe_code)]

mod errors;
mod namespace;
mod wrappers;

// Pulls in the Rust scaffolding generated by build.rs from
// `src/secretary.udl`. The argument must match the UDL `namespace` block.
//
// uniffi 0.31's scaffolding emits paths of the form `crate::TypeName`
// derived directly from the UDL declarations, so every type / function
// declared in the UDL must be re-exported at crate root. The `pub use`
// blocks below satisfy that contract.
uniffi::include_scaffolding!("secretary");

pub use errors::{UnlockError, VaultError};
pub use namespace::{
    add_device_slot, append_record, create_block, create_vault, create_vault_in_folder,
    edit_record, import_contact_card, move_record, open_vault_with_password,
    open_vault_with_recovery, open_with_device_secret, open_with_password, open_with_recovery,
    preview_repair_with_device_secret, preview_repair_with_password, preview_repair_with_recovery,
    purge_block, read_block, remove_device_slot, rename_block, repair_with_device_secret,
    repair_with_password, repair_with_recovery, restore_block, resurrect_record, save_block,
    share_block, share_block_to, sync_commit_decisions, sync_status, sync_vault, tombstone_record,
    trash_block,
};
pub use wrappers::block::{BlockReadOutput, FieldHandle, Record};
pub use wrappers::device::{DeviceEnrollOutput, DeviceSecretOutput};
pub use wrappers::identity::{
    CreateVaultOutput, CreatedVaultInFolder, MnemonicOutput, UnlockedIdentity,
};
pub use wrappers::purge::PurgeReport;
pub use wrappers::save::{BlockInput, FieldInput, FieldInputValue, RecordContent, RecordInput};
pub use wrappers::sync::{
    CollisionDto, DeviceClockDto, SyncOutcomeDto, SyncStatusDto, VetoDecisionDto, VetoDto,
};
pub use wrappers::vault::{BlockSummary, OpenVaultManifest, OpenVaultOutput};
pub use wrappers::{
    AddedRecipient, ApprovedWidening, ContactSummary, RepairPreview, WideningReport,
};

/// Smoke test: returns the vault format version exposed by the core crate.
///
/// Mirrors the Python crate's `version()` for parity across the two
/// binding flavors. B.1.1 keeps it as a Rust free function so the unit
/// tests below can exercise it without going through uniffi.
pub fn version() -> u16 {
    secretary_core::version::FORMAT_VERSION
}

/// Smoke-test addition. B.1.1 round-trip target.
///
/// Uses `wrapping_add` to make the overflow contract explicit (matches
/// default Rust `+` semantics in release builds, which silently wrap),
/// matching the Python crate's `add` contract for cross-binding parity.
pub fn add(a: u32, b: u32) -> u32 {
    a.wrapping_add(b)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_returns_format_version() {
        assert_eq!(version(), secretary_core::version::FORMAT_VERSION);
    }

    #[test]
    fn add_returns_arithmetic_sum() {
        assert_eq!(add(2, 3), 5);
    }

    #[test]
    fn add_wraps_on_overflow() {
        // Pin the wrapping contract: u32::MAX + 1 wraps to 0. A future
        // change to checked_add / saturating_add (or a switch to a fallible
        // signature in B.2) is a deliberate test failure rather than a
        // silent contract change.
        assert_eq!(add(u32::MAX, 1), 0);
    }
}
