//! uniffi bindings for secretary-core.
//!
//! The crate-level `#![allow(unsafe_code)]` is the minimal escape hatch
//! for `uniffi::include_scaffolding!()`, which expands to the generated
//! `secretary.uniffi.rs` file in `OUT_DIR` containing `unsafe extern "C"`
//! blocks (the FFI bridge to the C ABI is inherently unsafe). The
//! crate-local lint relaxation (workspace `forbid` → crate-local `deny`)
//! is required because `forbid` is non-overridable by inner `#[allow]`;
//! see Cargo.toml.
//!
//! The `#[allow]` is **crate-level** rather than item-level because the
//! `include_scaffolding!()` macro generates code at crate scope (the
//! generated file declares `extern "C"` symbols and free functions). A
//! narrower item-level `#[allow]` doesn't cover that expansion. The
//! tradeoff: a future contributor who adds a hand-rolled `unsafe` block
//! anywhere in this crate gets silence rather than a `deny` error. The
//! crate is intentionally tiny and reviewed; new `unsafe` blocks should
//! be challenged in code review.
//!
//! Rationale: secretary_next_session.md "Begin Sub-project B.1.1".
//!
//! B.3a (this version) adds the `open_with_recovery` namespace function
//! and 2 new `UnlockError` variants (`WrongMnemonicOrCorrupt`,
//! `InvalidMnemonic { detail }`). Mnemonic input is UTF-8 bytes; the
//! bridge's UTF-8 validation seam surfaces malformed input as
//! `InvalidMnemonic`.
//!
//! Rationale (B.3a): docs/superpowers/specs/2026-05-04-ffi-b3a-recovery-unlock-design.md
//!
//! B.3b adds the `create_vault` namespace function and 2 new opaque-
//! handle types (`CreateVaultOutput` dictionary, `MnemonicOutput`
//! interface). Bridge instantiates `OsRng` and
//! `Argon2idParams::V1_DEFAULT` internally; foreign callers get
//! neither knob. Recovery mnemonic crosses back via
//! `MnemonicOutput.take_phrase()` as `sequence<u8>?` (one-shot;
//! second call returns null).
//!
//! Rationale (B.3b): docs/superpowers/specs/2026-05-05-ffi-b3b-create-vault-design.md

#![allow(unsafe_code)]

// Pulls in the Rust scaffolding generated by build.rs from
// `src/secretary.udl`. The argument must match the UDL `namespace` block.
uniffi::include_scaffolding!("secretary");

/// Smoke test: returns the vault format version exposed by the core crate.
///
/// Mirrors the Python crate's `version()` for parity across the two
/// binding flavors. B.1.1 keeps it as a Rust free function so the unit
/// tests below can exercise it without going through uniffi.
pub fn version() -> u16 {
    secretary_core::version::FORMAT_VERSION
}

/// Smoke-test addition. B.1.1 round-trip target.
///
/// Uses `wrapping_add` to make the overflow contract explicit (matches
/// default Rust `+` semantics in release builds, which silently wrap),
/// matching the Python crate's `add` contract for cross-binding parity.
/// B.2 will reconsider when fallible crypto operations make uniffi's
/// error-marshalling story first-class.
pub fn add(a: u32, b: u32) -> u32 {
    a.wrapping_add(b)
}

// ---------------------------------------------------------------------------
// B.2: open_with_password + UnlockedIdentity + UnlockError.
//
// The actual logic lives in secretary-ffi-bridge; this file is the uniffi
// projection layer.
// ---------------------------------------------------------------------------

use secretary_ffi_bridge::FfiUnlockError;
use zeroize::Zeroize;

/// uniffi-side error type. uniffi auto-marshals this to Swift `enum
/// UnlockError: Error` and Kotlin `sealed class UnlockError`. Mirrors
/// the bridge crate's `FfiUnlockError` shape exactly.
///
/// The structured field is named `detail` rather than `message` because
/// uniffi 0.31's Kotlin codegen produces an "overload resolution
/// ambiguity" between `Throwable.message` and a user-defined `message`
/// field. `detail` keeps the field structured-accessible on Swift /
/// Kotlin while avoiding the codegen collision. The field name must
/// stay in sync with `secretary.udl`.
#[derive(Debug, thiserror::Error)]
pub enum UnlockError {
    /// Wrong password OR vault corruption — deliberately conflated per
    /// `docs/threat-model.md` §13. Returned by `open_with_password`.
    #[error("wrong password or vault corruption")]
    WrongPasswordOrCorrupt,
    /// Wrong recovery phrase OR vault corruption — parallel to the password
    /// path. Returned by `open_with_recovery`.
    #[error("wrong recovery phrase or vault corruption")]
    WrongMnemonicOrCorrupt,
    /// Invalid recovery phrase — pre-decryption BIP-39 validation failure
    /// (wrong word count, unknown word, bad checksum, or invalid UTF-8).
    /// NOT a security oracle.
    #[error("invalid recovery phrase: {detail}")]
    InvalidMnemonic {
        /// Diagnostic text; free-form.
        detail: String,
    },
    /// `vault.toml` and `identity.bundle.enc` reference different vaults.
    #[error("vault.toml and identity.bundle.enc reference different vaults")]
    VaultMismatch,
    /// Vault data integrity failure — covers BOTH directions: open-path
    /// failure (vault file is malformed / unreadable) AND create-path
    /// failure (couldn't even produce the vault bytes; rare, e.g. Argon2id
    /// system-OOM or CBOR serialization failure of the in-memory bundle).
    /// Carries a diagnostic `detail` string for debugging; not
    /// pattern-matchable on the inner cause.
    #[error("vault data integrity failure: {detail}")]
    CorruptVault {
        /// Diagnostic text from the inner `core::UnlockError` variant's
        /// `Display` impl. Free-form; not part of the API contract.
        detail: String,
    },
}

impl From<FfiUnlockError> for UnlockError {
    fn from(e: FfiUnlockError) -> Self {
        match e {
            FfiUnlockError::WrongPasswordOrCorrupt => Self::WrongPasswordOrCorrupt,
            FfiUnlockError::WrongMnemonicOrCorrupt => Self::WrongMnemonicOrCorrupt,
            FfiUnlockError::InvalidMnemonic { detail } => Self::InvalidMnemonic { detail },
            FfiUnlockError::VaultMismatch => Self::VaultMismatch,
            FfiUnlockError::CorruptVault { detail } => Self::CorruptVault { detail },
        }
    }
}

/// uniffi-side opaque handle. Newtype around bridge's `UnlockedIdentity`;
/// methods are thin forwarders. Drops on foreign refcount → 0 (RAII safety
/// net via uniffi's generated `AutoCloseable.close()` on Kotlin /
/// `deinit` on Swift) or via explicit `wipe()` (preferred — zeroizes
/// the wrapped secrets at exactly the moment of the call).
///
/// The explicit-zeroize method is named `wipe` rather than `close` to
/// avoid colliding with uniffi's auto-generated Kotlin
/// `AutoCloseable.close()`; see `secretary.udl` for the rationale.
pub struct UnlockedIdentity(secretary_ffi_bridge::UnlockedIdentity);

impl UnlockedIdentity {
    /// User-facing display name. Returns `""` if the handle has been wiped.
    pub fn display_name(&self) -> String {
        self.0.display_name()
    }

    /// 16-byte stable identifier. Returns 16 zero bytes if wiped.
    pub fn user_uuid(&self) -> Vec<u8> {
        self.0.user_uuid()
    }

    /// Drop the wrapped identity now, zeroizing all secret fields. Idempotent.
    pub fn wipe(&self) {
        self.0.close();
    }
}

/// uniffi-side opaque-handle wrapper around
/// `secretary_ffi_bridge::MnemonicOutput`. Newtype; methods are thin
/// forwarders.
///
/// One-shot semantics: `take_phrase()` returns `Some(bytes)` once, then
/// `None` on every subsequent call. `wipe()` is idempotent.
///
/// The explicit-zeroize method is named `wipe` rather than `close` for
/// the same reason as `UnlockedIdentity`: uniffi 0.31's Kotlin codegen
/// auto-generates an `AutoCloseable.close()` and a UDL-declared
/// `close()` would collide.
pub struct MnemonicOutput(secretary_ffi_bridge::MnemonicOutput);

impl MnemonicOutput {
    /// Take the recovery phrase as UTF-8 bytes. ONE-SHOT — second call
    /// returns `None`. Bytes are caller-owned heap; caller MUST zeroize
    /// after use.
    pub fn take_phrase(&self) -> Option<Vec<u8>> {
        self.0.take_phrase()
    }

    /// Drop any still-resident inner mnemonic now, zeroizing its
    /// `Sensitive<...>` fields. Idempotent.
    pub fn wipe(&self) {
        self.0.wipe();
    }
}

/// uniffi-side dictionary (struct-by-value) for `create_vault`'s return
/// shape. Two `Vec<u8>` (non-secret) plus two `Arc<Interface>` (uniffi
/// marshals interface-typed dictionary fields as `Arc` handles).
pub struct CreateVaultOutput {
    /// Vault metadata bytes — non-secret. Persist atomically.
    pub vault_toml_bytes: Vec<u8>,
    /// Encrypted identity bundle bytes — non-secret. Persist atomically.
    pub identity_bundle_bytes: Vec<u8>,
    /// Live opaque handle to the just-created identity. Ready for vault
    /// operations immediately; no second `open_with_password` call needed.
    pub identity: std::sync::Arc<UnlockedIdentity>,
    /// One-shot opaque handle for the recovery phrase.
    pub mnemonic: std::sync::Arc<MnemonicOutput>,
}

// =============================================================================
// B.4a — VaultError (mirrors FfiVaultError 6-variant flat enum)
// =============================================================================

/// uniffi projection of FfiVaultError + one extra variant for FFI input-
/// shape errors (`InvalidArgument`). Eight flat variants matching the UDL
/// declaration.
///
/// The structured-field rename rationale is the same as UnlockError's:
/// uniffi 0.31's Kotlin codegen has overload-resolution conflicts between
/// `Throwable.message` and a UDL-declared `message` field, so structured
/// fields are named `detail`.
///
/// The eighth variant `InvalidArgument` has no counterpart in the bridge's
/// `FfiVaultError` — it's uniffi-side only because uniffi 0.31 has no
/// native `ValueError` equivalent at the namespace-fn level, so wrong-
/// length / malformed FFI inputs (e.g. `block_uuid` ≠ 16 bytes) need to
/// ride inside `VaultError`. PyO3 raises Python `ValueError` for the
/// equivalent case (see `secretary-ffi-py/src/lib.rs::read_block`); the
/// dedicated uniffi variant keeps the semantic clean rather than abusing
/// `FolderInvalid` (which means "your filesystem path is wrong").
#[derive(Debug, thiserror::Error)]
pub enum VaultError {
    #[error("wrong password or vault corruption")]
    WrongPasswordOrCorrupt,
    #[error("wrong recovery phrase or vault corruption")]
    WrongMnemonicOrCorrupt,
    #[error("invalid recovery phrase: {detail}")]
    InvalidMnemonic { detail: String },
    #[error("vault.toml and identity.bundle.enc reference different vaults")]
    VaultMismatch,
    #[error("vault data integrity failure: {detail}")]
    CorruptVault { detail: String },
    #[error("vault folder is not accessible: {detail}")]
    FolderInvalid { detail: String },
    #[error("block not found in manifest: {uuid_hex}")]
    BlockNotFound { uuid_hex: String },
    #[error("invalid argument: {detail}")]
    InvalidArgument { detail: String },
}

impl From<secretary_ffi_bridge::FfiVaultError> for VaultError {
    fn from(e: secretary_ffi_bridge::FfiVaultError) -> Self {
        use secretary_ffi_bridge::FfiVaultError as B;
        match e {
            B::WrongPasswordOrCorrupt => VaultError::WrongPasswordOrCorrupt,
            B::WrongMnemonicOrCorrupt => VaultError::WrongMnemonicOrCorrupt,
            B::InvalidMnemonic { detail } => VaultError::InvalidMnemonic { detail },
            B::VaultMismatch => VaultError::VaultMismatch,
            B::CorruptVault { detail } => VaultError::CorruptVault { detail },
            B::FolderInvalid { detail } => VaultError::FolderInvalid { detail },
            B::BlockNotFound { uuid_hex } => VaultError::BlockNotFound { uuid_hex },
        }
    }
}

// =============================================================================
// B.4a — OpenVaultManifest (opaque handle wrapper)
// =============================================================================

/// uniffi wrapper around secretary_ffi_bridge::OpenVaultManifest.
pub struct OpenVaultManifest(secretary_ffi_bridge::OpenVaultManifest);

impl OpenVaultManifest {
    pub fn vault_uuid(&self) -> Vec<u8> {
        self.0.vault_uuid()
    }

    pub fn owner_user_uuid(&self) -> Vec<u8> {
        self.0.owner_user_uuid()
    }

    pub fn block_count(&self) -> u64 {
        self.0.block_count()
    }

    pub fn block_summaries(&self) -> Vec<BlockSummary> {
        self.0
            .block_summaries()
            .into_iter()
            .map(BlockSummary::from)
            .collect()
    }

    pub fn find_block(&self, block_uuid: Vec<u8>) -> Option<BlockSummary> {
        self.0.find_block(&block_uuid).map(BlockSummary::from)
    }

    pub fn wipe(&self) {
        self.0.wipe();
    }
}

// =============================================================================
// B.4b — BlockReadOutput / Record / FieldHandle wrappers
// =============================================================================

/// uniffi wrapper around secretary_ffi_bridge::BlockReadOutput. Newtype;
/// methods are thin forwarders. Drops on foreign refcount → 0 (RAII safety
/// net via uniffi-generated AutoCloseable.close() on Kotlin / deinit on
/// Swift) or via explicit wipe().
pub struct BlockReadOutput(secretary_ffi_bridge::BlockReadOutput);

impl BlockReadOutput {
    pub fn block_uuid(&self) -> Vec<u8> {
        self.0.block_uuid().to_vec()
    }
    pub fn block_name(&self) -> String {
        self.0.block_name()
    }
    pub fn record_count(&self) -> u64 {
        self.0.record_count() as u64
    }
    pub fn record_at(&self, idx: u64) -> Option<std::sync::Arc<Record>> {
        self.0
            .record_at(idx as usize)
            .map(|r| std::sync::Arc::new(Record(r)))
    }
    pub fn wipe(&self) {
        self.0.wipe();
    }
}

/// uniffi wrapper around secretary_ffi_bridge::Record.
pub struct Record(secretary_ffi_bridge::Record);

impl Record {
    pub fn record_uuid(&self) -> Vec<u8> {
        self.0.record_uuid().to_vec()
    }
    pub fn record_type(&self) -> String {
        self.0.record_type()
    }
    pub fn tags(&self) -> Vec<String> {
        self.0.tags()
    }
    pub fn created_at_ms(&self) -> u64 {
        self.0.created_at_ms()
    }
    pub fn last_mod_ms(&self) -> u64 {
        self.0.last_mod_ms()
    }
    pub fn tombstone(&self) -> bool {
        self.0.tombstone()
    }
    pub fn field_count(&self) -> u64 {
        self.0.field_count() as u64
    }
    pub fn field_names(&self) -> Vec<String> {
        self.0.field_names()
    }
    pub fn field_by_name(&self, name: String) -> Option<std::sync::Arc<FieldHandle>> {
        self.0
            .field_by_name(&name)
            .map(|f| std::sync::Arc::new(FieldHandle(f)))
    }
    pub fn field_at(&self, idx: u64) -> Option<std::sync::Arc<FieldHandle>> {
        self.0
            .field_at(idx as usize)
            .map(|f| std::sync::Arc::new(FieldHandle(f)))
    }
    pub fn wipe(&self) {
        self.0.wipe();
    }
}

/// uniffi wrapper around secretary_ffi_bridge::FieldHandle.
pub struct FieldHandle(secretary_ffi_bridge::FieldHandle);

impl FieldHandle {
    pub fn name(&self) -> String {
        self.0.name()
    }
    pub fn last_mod_ms(&self) -> u64 {
        self.0.last_mod_ms()
    }
    pub fn device_uuid(&self) -> Vec<u8> {
        self.0.device_uuid().to_vec()
    }
    pub fn is_text(&self) -> bool {
        self.0.is_text()
    }
    pub fn is_bytes(&self) -> bool {
        self.0.is_bytes()
    }
    pub fn expose_text(&self) -> Option<String> {
        self.0.expose_text()
    }
    pub fn expose_bytes(&self) -> Option<Vec<u8>> {
        self.0.expose_bytes()
    }
    pub fn wipe(&self) {
        self.0.wipe();
    }
}

// =============================================================================
// B.4a — BlockSummary value type (uniffi dictionary)
// =============================================================================

/// uniffi dictionary projection of secretary_ffi_bridge::BlockSummary.
pub struct BlockSummary {
    pub block_uuid: Vec<u8>,
    pub block_name: String,
    pub created_at_ms: u64,
    pub last_modified_ms: u64,
    pub recipient_uuids: Vec<Vec<u8>>,
}

impl From<secretary_ffi_bridge::BlockSummary> for BlockSummary {
    fn from(b: secretary_ffi_bridge::BlockSummary) -> Self {
        Self {
            block_uuid: b.block_uuid.to_vec(),
            block_name: b.block_name,
            created_at_ms: b.created_at_ms,
            last_modified_ms: b.last_modified_ms,
            recipient_uuids: b.recipient_uuids.into_iter().map(|u| u.to_vec()).collect(),
        }
    }
}

// =============================================================================
// B.4a — OpenVaultOutput dictionary
// =============================================================================

/// uniffi dictionary projection. Holds two opaque-handle Arc references.
/// Same shape as B.3b's CreateVaultOutput dictionary.
pub struct OpenVaultOutput {
    pub identity: std::sync::Arc<UnlockedIdentity>,
    pub manifest: std::sync::Arc<OpenVaultManifest>,
}

/// Unlock a vault using its master password. uniffi-projected.
///
/// # Errors
///
/// Returns [`UnlockError`] on failure. See the bridge crate's
/// [`FfiUnlockError`](secretary_ffi_bridge::FfiUnlockError) docs for the
/// thinned 5-variant rationale.
///
/// # Why `Arc<UnlockedIdentity>`?
///
/// uniffi marshals UDL `interface` types as refcounted handles on the
/// foreign side. The Rust signature must therefore return `Arc<T>` (uniffi
/// owns the refcount; the foreign caller's release decrements it). Without
/// the `Arc<>`, uniffi's generated scaffolding emits a type-mismatch error
/// (`expected Result<Arc<UnlockedIdentity>, ...>, found Result<UnlockedIdentity, _>`).
pub fn open_with_password(
    vault_toml_bytes: Vec<u8>,
    identity_bundle_bytes: Vec<u8>,
    mut password: Vec<u8>,
) -> Result<std::sync::Arc<UnlockedIdentity>, UnlockError> {
    // Mirrors the secretary-ffi-py wrapper's stack-residue discipline:
    // zero the password Vec after the bridge returns. The bridge already
    // zeroizes its SecretBytes copy; this wipes the projection-side
    // transient.
    let result = secretary_ffi_bridge::open_with_password(
        &vault_toml_bytes,
        &identity_bundle_bytes,
        &password,
    )
    .map(|inner| std::sync::Arc::new(UnlockedIdentity(inner)))
    .map_err(UnlockError::from);
    password.zeroize();
    result
}

/// Unlock a vault using its 24-word BIP-39 recovery phrase. uniffi-projected.
///
/// Mnemonic input is UTF-8-encoded bytes (`Vec<u8>`); the bridge's UTF-8
/// validation seam surfaces malformed-UTF-8 input as
/// [`UnlockError::InvalidMnemonic`] with `detail: "phrase contained
/// invalid UTF-8"`.
///
/// # Errors
///
/// Returns [`UnlockError`] on failure. See the bridge crate's
/// [`FfiUnlockError`](secretary_ffi_bridge::FfiUnlockError) docs for the
/// thinned 5-variant rationale.
pub fn open_with_recovery(
    vault_toml_bytes: Vec<u8>,
    identity_bundle_bytes: Vec<u8>,
    mut mnemonic: Vec<u8>,
) -> Result<std::sync::Arc<UnlockedIdentity>, UnlockError> {
    // Mirrors the open_with_password wrapper-side stack-residue discipline:
    // zero the mnemonic Vec after the bridge returns. The bridge takes &[u8]
    // and never retains; this Vec is the projection-side transient.
    let result = secretary_ffi_bridge::open_with_recovery(
        &vault_toml_bytes,
        &identity_bundle_bytes,
        &mnemonic,
    )
    .map(|inner| std::sync::Arc::new(UnlockedIdentity(inner)))
    .map_err(UnlockError::from);
    mnemonic.zeroize();
    result
}

/// Create a fresh v1 vault. uniffi-projected. (B.3b)
///
/// The bridge crate instantiates `OsRng` and
/// `Argon2idParams::V1_DEFAULT` internally; foreign callers cannot tune
/// either.
///
/// Returns a [`CreateVaultOutput`] containing on-disk byte artifacts and
/// two opaque handles ([`UnlockedIdentity`] and [`MnemonicOutput`]).
///
/// # Errors
///
/// Returns [`UnlockError`] on failure. See the bridge crate's
/// [`FfiUnlockError`](secretary_ffi_bridge::FfiUnlockError) docs for the
/// thinned 5-variant rationale.
pub fn create_vault(
    mut password: Vec<u8>,
    display_name: String,
    created_at_ms: u64,
) -> Result<CreateVaultOutput, UnlockError> {
    // Mirrors the open_with_password / open_with_recovery wrapper-side
    // stack-residue discipline: zero the password Vec after the bridge
    // returns. The bridge takes &[u8] and never retains; this Vec is the
    // projection-side transient.
    let result = secretary_ffi_bridge::create_vault(&password, &display_name, created_at_ms);
    password.zeroize();

    let bridge_out = result.map_err(UnlockError::from)?;

    let secretary_ffi_bridge::CreateVaultOutput {
        vault_toml_bytes,
        identity_bundle_bytes,
        identity,
        mnemonic,
    } = bridge_out;

    Ok(CreateVaultOutput {
        vault_toml_bytes,
        identity_bundle_bytes,
        identity: std::sync::Arc::new(UnlockedIdentity(identity)),
        mnemonic: std::sync::Arc::new(MnemonicOutput(mnemonic)),
    })
}

/// Open a vault folder using its master password. uniffi-projected. (B.4a)
///
/// `folder_path` is the UTF-8-encoded filesystem path to the vault folder as
/// bytes. Returns [`VaultError::FolderInvalid`] if the path contains invalid
/// UTF-8.
///
/// # Errors
///
/// Returns [`VaultError`] on failure. See the bridge crate's
/// [`FfiVaultError`](secretary_ffi_bridge::FfiVaultError) docs for the
/// thinned 6-variant rationale.
pub fn open_vault_with_password(
    folder_path: Vec<u8>,
    mut password: Vec<u8>,
) -> Result<OpenVaultOutput, VaultError> {
    use zeroize::Zeroize;

    // Compute the full result chain (path validation + bridge call) into a
    // single binding so we can zeroize the password BEFORE any `?`-propagation.
    // Both fallible paths produce the same Err type, so there is no lost
    // context in the match arms.
    let result: Result<secretary_ffi_bridge::OpenVaultOutput, VaultError> =
        match std::str::from_utf8(&folder_path) {
            Ok(s) => {
                let path = std::path::PathBuf::from(s);
                secretary_ffi_bridge::open_vault_with_password(&path, &password)
                    .map_err(VaultError::from)
            }
            Err(_) => Err(VaultError::FolderInvalid {
                detail: "folder path contained invalid UTF-8".to_string(),
            }),
        };

    // Zeroize unconditionally — runs on both success and error paths.
    password.zeroize();

    let bridge_out = result?;
    Ok(OpenVaultOutput {
        identity: std::sync::Arc::new(UnlockedIdentity(bridge_out.identity)),
        manifest: std::sync::Arc::new(OpenVaultManifest(bridge_out.manifest)),
    })
}

/// Open a vault folder using its 24-word BIP-39 recovery phrase. uniffi-projected. (B.4a)
///
/// `folder_path` is the UTF-8-encoded filesystem path as bytes.
/// `mnemonic` is the UTF-8-encoded phrase as bytes; the bridge's UTF-8
/// validation seam surfaces malformed-UTF-8 input as
/// [`VaultError::InvalidMnemonic`] with `detail: "phrase contained invalid UTF-8"`.
///
/// # Errors
///
/// Returns [`VaultError`] on failure.
pub fn open_vault_with_recovery(
    folder_path: Vec<u8>,
    mut mnemonic: Vec<u8>,
) -> Result<OpenVaultOutput, VaultError> {
    use zeroize::Zeroize;

    // Compute the full result chain (path validation + bridge call) into a
    // single binding so we can zeroize the mnemonic BEFORE any `?`-propagation.
    // Both fallible paths produce the same Err type, so there is no lost
    // context in the match arms.
    let result: Result<secretary_ffi_bridge::OpenVaultOutput, VaultError> =
        match std::str::from_utf8(&folder_path) {
            Ok(s) => {
                let path = std::path::PathBuf::from(s);
                secretary_ffi_bridge::open_vault_with_recovery(&path, &mnemonic)
                    .map_err(VaultError::from)
            }
            Err(_) => Err(VaultError::FolderInvalid {
                detail: "folder path contained invalid UTF-8".to_string(),
            }),
        };

    // Zeroize unconditionally — runs on both success and error paths.
    mnemonic.zeroize();

    let bridge_out = result?;
    Ok(OpenVaultOutput {
        identity: std::sync::Arc::new(UnlockedIdentity(bridge_out.identity)),
        manifest: std::sync::Arc::new(OpenVaultManifest(bridge_out.manifest)),
    })
}

/// Decrypt one block of an open vault and return its records. (B.4b)
///
/// `block_uuid` must be exactly 16 bytes; otherwise returns
/// [`VaultError::InvalidArgument`] (uniffi 0.31 has no native `ValueError`
/// equivalent at the namespace-fn level, so the FFI input-shape error
/// rides inside `VaultError` — but in a dedicated variant rather than
/// folded into `FolderInvalid`, which semantically means "your filesystem
/// path is wrong").
///
/// # Errors
///
/// - [`VaultError::InvalidArgument`] — wrong-length `block_uuid` (≠ 16 bytes).
/// - [`VaultError::BlockNotFound`] — UUID not in manifest's live blocks list.
/// - [`VaultError::CorruptVault`] — block file missing/malformed/decryption failed.
/// - [`VaultError::FolderInvalid`] — block file present but unreadable
///   for non-NotFound IO reasons.
pub fn read_block(
    identity: std::sync::Arc<UnlockedIdentity>,
    manifest: std::sync::Arc<OpenVaultManifest>,
    block_uuid: Vec<u8>,
) -> Result<std::sync::Arc<BlockReadOutput>, VaultError> {
    if block_uuid.len() != 16 {
        return Err(VaultError::InvalidArgument {
            detail: format!("block_uuid must be 16 bytes, got {}", block_uuid.len()),
        });
    }
    let mut uuid_array = [0u8; 16];
    uuid_array.copy_from_slice(&block_uuid);
    secretary_ffi_bridge::read_block(&identity.0, &manifest.0, &uuid_array)
        .map(|b| std::sync::Arc::new(BlockReadOutput(b)))
        .map_err(VaultError::from)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_returns_format_version() {
        assert_eq!(version(), secretary_core::version::FORMAT_VERSION);
    }

    #[test]
    fn add_returns_arithmetic_sum() {
        assert_eq!(add(2, 3), 5);
    }

    #[test]
    fn add_wraps_on_overflow() {
        // Pin the wrapping contract: u32::MAX + 1 wraps to 0. A future
        // change to checked_add / saturating_add (or a switch to a fallible
        // signature in B.2) is a deliberate test failure rather than a
        // silent contract change.
        assert_eq!(add(u32::MAX, 1), 0);
    }

    // -------------------------------------------------------------------
    // B.2: pin the From<FfiUnlockError> for UnlockError mapping.
    //
    // The bridge crate already tests core → FfiUnlockError; these three
    // tests pin the FfiUnlockError → uniffi-side UnlockError translation
    // explicitly so a future variant rename / reorder can't silently
    // remap one variant to another.
    // -------------------------------------------------------------------

    #[test]
    fn from_bridge_wrong_password_or_corrupt_maps_one_to_one() {
        let bridge_err = FfiUnlockError::WrongPasswordOrCorrupt;
        let uniffi_err: UnlockError = bridge_err.into();
        assert!(matches!(uniffi_err, UnlockError::WrongPasswordOrCorrupt));
    }

    #[test]
    fn from_bridge_vault_mismatch_maps_one_to_one() {
        let bridge_err = FfiUnlockError::VaultMismatch;
        let uniffi_err: UnlockError = bridge_err.into();
        assert!(matches!(uniffi_err, UnlockError::VaultMismatch));
    }

    #[test]
    fn from_bridge_corrupt_vault_preserves_detail() {
        // B.3a renamed the bridge's CorruptVault field from `message` to
        // `detail` for naming uniformity with InvalidMnemonic { detail }.
        // Both layers now use `detail`; the From translation is a struct-
        // shorthand pass-through.
        let bridge_err = FfiUnlockError::CorruptVault {
            detail: "fnord".to_string(),
        };
        let uniffi_err: UnlockError = bridge_err.into();
        let UnlockError::CorruptVault { detail } = uniffi_err else {
            panic!("expected CorruptVault");
        };
        assert_eq!(detail, "fnord");
    }

    #[test]
    fn from_bridge_wrong_mnemonic_or_corrupt_maps_one_to_one() {
        let bridge_err = FfiUnlockError::WrongMnemonicOrCorrupt;
        let uniffi_err: UnlockError = bridge_err.into();
        assert!(matches!(uniffi_err, UnlockError::WrongMnemonicOrCorrupt));
    }

    #[test]
    fn from_bridge_invalid_mnemonic_preserves_detail() {
        let bridge_err = FfiUnlockError::InvalidMnemonic {
            detail: "expected 24 words, got 3".to_string(),
        };
        let uniffi_err: UnlockError = bridge_err.into();
        let UnlockError::InvalidMnemonic { detail } = uniffi_err else {
            panic!("expected InvalidMnemonic");
        };
        assert_eq!(detail, "expected 24 words, got 3");
    }

    #[test]
    fn corrupt_vault_display_uses_path_neutral_text() {
        // Mirror of the bridge crate's tripwire (see ffi/secretary-ffi-bridge/
        // src/error.rs). The uniffi-side UnlockError carries its own Display
        // attributes (because uniffi codegen uses this enum to produce the
        // Swift / Kotlin error messages); this test pins the path-neutral
        // wording so a future revert here is a deliberate decision.
        let err = UnlockError::CorruptVault {
            detail: "fnord".to_string(),
        };
        let rendered = format!("{err}");
        assert!(
            rendered.contains("vault data integrity failure"),
            "Display did not contain the path-neutral text: {rendered}",
        );
        assert!(rendered.contains("fnord"), "Display did not include detail");
        assert!(
            !rendered.contains("corrupt or unreadable"),
            "Display still contains the old read-path-only text: {rendered}",
        );
    }

    // -------------------------------------------------------------------
    // B.3b: uniffi-side projection of create_vault.
    //
    // The bridge crate already covers MnemonicOutput contract semantics
    // in isolation (one-shot take_phrase, idempotent wipe, 24-word phrase).
    // The two tests below pin the uniffi-layer wrapper plumbing only:
    // one slow integration test (real Argon2id) and one fast wrapper test
    // (synthesized MnemonicOutput, no Argon2id).
    // -------------------------------------------------------------------

    #[test]
    fn create_vault_returns_live_identity_and_mnemonic() {
        // Slow test: real Argon2id. ~1s. Sole uniffi-layer integration test
        // for create_vault; the bridge crate already covers MnemonicOutput
        // contract semantics in isolation.
        let out = create_vault(
            b"hunter2".to_vec(),
            "UniffiTest".to_string(),
            1_700_000_000_000,
        )
        .expect("create_vault should succeed");
        assert_eq!(out.identity.display_name(), "UniffiTest");
        assert_eq!(out.identity.user_uuid().len(), 16);
        assert!(!out.vault_toml_bytes.is_empty());
        assert!(!out.identity_bundle_bytes.is_empty());

        let phrase = out.mnemonic.take_phrase().expect("phrase available");
        assert_eq!(
            phrase.split(|&b| b == b' ').count(),
            24,
            "expected 24-word phrase",
        );

        let second = out.mnemonic.take_phrase();
        assert!(second.is_none(), "second take_phrase must return None");
    }

    #[test]
    fn mnemonic_output_wipe_is_idempotent_through_uniffi_wrapper() {
        // Fast test: synthesize a MnemonicOutput from a seeded mnemonic
        // generation. No Argon2id; checks the wrapper plumbing only.
        use rand_chacha::{rand_core::SeedableRng, ChaCha20Rng};
        use secretary_core::unlock::mnemonic;
        let mut rng = ChaCha20Rng::from_seed([7u8; 32]);
        let m = mnemonic::generate(&mut rng);
        let bridge_mo = secretary_ffi_bridge::MnemonicOutput::new_for_test(m);
        let mo = MnemonicOutput(bridge_mo);
        mo.wipe();
        mo.wipe(); // must not panic
        assert!(mo.take_phrase().is_none());
    }

    // -------------------------------------------------------------------
    // B.4a: pin the From<FfiVaultError> for VaultError mapping and
    // BlockSummary projection.
    // -------------------------------------------------------------------

    #[test]
    fn vault_error_maps_each_variant_one_to_one() {
        use secretary_ffi_bridge::FfiVaultError as B;
        assert!(matches!(
            VaultError::from(B::WrongPasswordOrCorrupt),
            VaultError::WrongPasswordOrCorrupt
        ));
        assert!(matches!(
            VaultError::from(B::WrongMnemonicOrCorrupt),
            VaultError::WrongMnemonicOrCorrupt
        ));
        let inv = VaultError::from(B::InvalidMnemonic {
            detail: "x".to_string(),
        });
        let VaultError::InvalidMnemonic { detail } = inv else {
            panic!("expected InvalidMnemonic")
        };
        assert_eq!(detail, "x");
        assert!(matches!(
            VaultError::from(B::VaultMismatch),
            VaultError::VaultMismatch
        ));
        let cor = VaultError::from(B::CorruptVault {
            detail: "y".to_string(),
        });
        let VaultError::CorruptVault { detail } = cor else {
            panic!("expected CorruptVault")
        };
        assert_eq!(detail, "y");
        let fol = VaultError::from(B::FolderInvalid {
            detail: "z".to_string(),
        });
        let VaultError::FolderInvalid { detail } = fol else {
            panic!("expected FolderInvalid")
        };
        assert_eq!(detail, "z");
    }

    #[test]
    fn block_summary_projection_round_trip_preserves_all_fields() {
        let bridge = secretary_ffi_bridge::BlockSummary {
            block_uuid: [1u8; 16],
            block_name: "test".to_string(),
            created_at_ms: 100,
            last_modified_ms: 200,
            recipient_uuids: vec![[2u8; 16], [3u8; 16]],
        };
        let proj = BlockSummary::from(bridge);
        assert_eq!(proj.block_uuid, vec![1u8; 16]);
        assert_eq!(proj.block_name, "test");
        assert_eq!(proj.created_at_ms, 100);
        assert_eq!(proj.last_modified_ms, 200);
        assert_eq!(proj.recipient_uuids, vec![vec![2u8; 16], vec![3u8; 16]]);
    }

    // -------------------------------------------------------------------
    // B.4a memory-hygiene regression: invalid-UTF-8 folder_path must
    // return FolderInvalid regardless of whether the secret arg is valid.
    //
    // The structural fix (zeroize before `?`-propagation) is enforced by
    // code shape; these tests pin the observable error contract so that a
    // future refactor that re-introduces `?`-before-zeroize also breaks
    // a named test rather than silently regressing.
    // -------------------------------------------------------------------

    #[test]
    fn open_vault_with_password_invalid_utf8_path_returns_folder_invalid() {
        // \xff\xfe is invalid UTF-8; the function must return FolderInvalid
        // rather than panicking or returning a different variant.
        // OpenVaultOutput doesn't implement Debug (it holds Arc<opaque handles>),
        // so we match rather than calling unwrap_err().
        match open_vault_with_password(b"\xff\xfe".to_vec(), b"hunter2".to_vec()) {
            Err(VaultError::FolderInvalid { .. }) => {}
            Err(other) => panic!("expected FolderInvalid, got {other:?}"),
            Ok(_) => panic!("expected Err for invalid UTF-8 path"),
        }
    }

    #[test]
    fn open_vault_with_recovery_invalid_utf8_path_returns_folder_invalid() {
        // Mirror of the password variant — pins the mnemonic forwarder.
        match open_vault_with_recovery(
            b"\xff\xfe".to_vec(),
            b"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about".to_vec(),
        ) {
            Err(VaultError::FolderInvalid { .. }) => {}
            Err(other) => panic!("expected FolderInvalid, got {other:?}"),
            Ok(_) => panic!("expected Err for invalid UTF-8 path"),
        }
    }

    // -------------------------------------------------------------------
    // B.4b: pin the BlockNotFound variant translation + the wrong-length
    // block_uuid → FolderInvalid decision (uniffi has no native ValueError
    // equivalent at the namespace-fn level; see read_block doc comment).
    // -------------------------------------------------------------------

    #[test]
    fn vault_error_block_not_found_maps_one_to_one() {
        // Pin the 7th variant translation. A future rename would fail
        // here first.
        use secretary_ffi_bridge::FfiVaultError as B;
        let bnf = VaultError::from(B::BlockNotFound {
            uuid_hex: "abc123".to_string(),
        });
        let VaultError::BlockNotFound { uuid_hex } = bnf else {
            panic!("expected BlockNotFound");
        };
        assert_eq!(uuid_hex, "abc123");
    }

    #[test]
    fn read_block_wrong_length_returns_invalid_argument() {
        // Pin the wrong-length-folds-to-InvalidArgument decision (PR #31
        // review feedback: was previously FolderInvalid, but that variant
        // semantically means "your filesystem path is wrong" — wrong-
        // length block_uuid is a programmer error and now surfaces through
        // the dedicated InvalidArgument variant instead).
        // Synthesize stub Arc<UnlockedIdentity> + Arc<OpenVaultManifest>
        // by routing through the real open path against golden_vault_001.
        // BlockReadOutput doesn't implement Debug (it holds zeroize-sensitive
        // wrappers), so we match rather than calling unwrap_err().
        let folder_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../core/tests/data/golden_vault_001");
        let folder_bytes = folder_path.to_str().unwrap().as_bytes().to_vec();
        let pwd = b"correct horse battery staple".to_vec();
        let out = open_vault_with_password(folder_bytes, pwd).unwrap();
        match read_block(out.identity, out.manifest, vec![0u8; 15]) {
            Err(VaultError::InvalidArgument { detail }) => {
                assert!(
                    detail.contains("16 bytes") && detail.contains("got 15"),
                    "detail did not mention length: {detail}",
                );
            }
            Err(other) => panic!("expected InvalidArgument for wrong-length, got {other:?}"),
            Ok(_) => panic!("expected Err for wrong-length block_uuid"),
        }
    }

    #[test]
    fn invalid_argument_display_pins_detail_text() {
        // Pin the Display contract for the new uniffi-only variant. uniffi
        // 0.31 codegen uses the #[error(...)] attribute to drive the
        // Swift / Kotlin generated message text; a future rename of the
        // attribute would silently change the foreign-side exception
        // message and must be a deliberate decision.
        let err = VaultError::InvalidArgument {
            detail: "fnord".to_string(),
        };
        let rendered = format!("{err}");
        assert!(
            rendered.contains("invalid argument"),
            "Display did not contain the InvalidArgument prefix: {rendered}",
        );
        assert!(rendered.contains("fnord"), "Display did not include detail");
    }
}
