//! uniffi bindings for secretary-core.
//!
//! The crate-level `#![allow(unsafe_code)]` is the minimal escape hatch
//! for `uniffi::include_scaffolding!()`, which expands to the generated
//! `secretary.uniffi.rs` file in `OUT_DIR` containing `unsafe extern "C"`
//! blocks (the FFI bridge to the C ABI is inherently unsafe). The
//! crate-local lint relaxation (workspace `forbid` → crate-local `deny`)
//! is required because `forbid` is non-overridable by inner `#[allow]`;
//! see Cargo.toml.
//!
//! The `#[allow]` is **crate-level** rather than item-level because the
//! `include_scaffolding!()` macro generates code at crate scope (the
//! generated file declares `extern "C"` symbols and free functions). A
//! narrower item-level `#[allow]` doesn't cover that expansion. The
//! tradeoff: a future contributor who adds a hand-rolled `unsafe` block
//! anywhere in this crate gets silence rather than a `deny` error. The
//! crate is intentionally tiny and reviewed; new `unsafe` blocks should
//! be challenged in code review.
//!
//! Rationale: secretary_next_session.md "Begin Sub-project B.1.1".
//!
//! B.3a (this version) adds the `open_with_recovery` namespace function
//! and 2 new `UnlockError` variants (`WrongMnemonicOrCorrupt`,
//! `InvalidMnemonic { detail }`). Mnemonic input is UTF-8 bytes; the
//! bridge's UTF-8 validation seam surfaces malformed input as
//! `InvalidMnemonic`.
//!
//! Rationale (B.3a): docs/superpowers/specs/2026-05-04-ffi-b3a-recovery-unlock-design.md
//!
//! B.3b adds the `create_vault` namespace function and 2 new opaque-
//! handle types (`CreateVaultOutput` dictionary, `MnemonicOutput`
//! interface). Bridge instantiates `OsRng` and
//! `Argon2idParams::V1_DEFAULT` internally; foreign callers get
//! neither knob. Recovery mnemonic crosses back via
//! `MnemonicOutput.take_phrase()` as `sequence<u8>?` (one-shot;
//! second call returns null).
//!
//! Rationale (B.3b): docs/superpowers/specs/2026-05-05-ffi-b3b-create-vault-design.md

#![allow(unsafe_code)]

// Pulls in the Rust scaffolding generated by build.rs from
// `src/secretary.udl`. The argument must match the UDL `namespace` block.
uniffi::include_scaffolding!("secretary");

/// Smoke test: returns the vault format version exposed by the core crate.
///
/// Mirrors the Python crate's `version()` for parity across the two
/// binding flavors. B.1.1 keeps it as a Rust free function so the unit
/// tests below can exercise it without going through uniffi.
pub fn version() -> u16 {
    secretary_core::version::FORMAT_VERSION
}

/// Smoke-test addition. B.1.1 round-trip target.
///
/// Uses `wrapping_add` to make the overflow contract explicit (matches
/// default Rust `+` semantics in release builds, which silently wrap),
/// matching the Python crate's `add` contract for cross-binding parity.
/// B.2 will reconsider when fallible crypto operations make uniffi's
/// error-marshalling story first-class.
pub fn add(a: u32, b: u32) -> u32 {
    a.wrapping_add(b)
}

// ---------------------------------------------------------------------------
// B.2: open_with_password + UnlockedIdentity + UnlockError.
//
// The actual logic lives in secretary-ffi-bridge; this file is the uniffi
// projection layer.
// ---------------------------------------------------------------------------

use secretary_ffi_bridge::FfiUnlockError;
use zeroize::Zeroize;

/// uniffi-side error type. uniffi auto-marshals this to Swift `enum
/// UnlockError: Error` and Kotlin `sealed class UnlockError`. Mirrors
/// the bridge crate's `FfiUnlockError` shape exactly.
///
/// The structured field is named `detail` rather than `message` because
/// uniffi 0.31's Kotlin codegen produces an "overload resolution
/// ambiguity" between `Throwable.message` and a user-defined `message`
/// field. `detail` keeps the field structured-accessible on Swift /
/// Kotlin while avoiding the codegen collision. The field name must
/// stay in sync with `secretary.udl`.
#[derive(Debug, thiserror::Error)]
pub enum UnlockError {
    /// Wrong password OR vault corruption — deliberately conflated per
    /// `docs/threat-model.md` §13. Returned by `open_with_password`.
    #[error("wrong password or vault corruption")]
    WrongPasswordOrCorrupt,
    /// Wrong recovery phrase OR vault corruption — parallel to the password
    /// path. Returned by `open_with_recovery`.
    #[error("wrong recovery phrase or vault corruption")]
    WrongMnemonicOrCorrupt,
    /// Invalid recovery phrase — pre-decryption BIP-39 validation failure
    /// (wrong word count, unknown word, bad checksum, or invalid UTF-8).
    /// NOT a security oracle.
    #[error("invalid recovery phrase: {detail}")]
    InvalidMnemonic {
        /// Diagnostic text; free-form.
        detail: String,
    },
    /// `vault.toml` and `identity.bundle.enc` reference different vaults.
    #[error("vault.toml and identity.bundle.enc reference different vaults")]
    VaultMismatch,
    /// Vault data integrity failure — covers BOTH directions: open-path
    /// failure (vault file is malformed / unreadable) AND create-path
    /// failure (couldn't even produce the vault bytes; rare, e.g. Argon2id
    /// system-OOM or CBOR serialization failure of the in-memory bundle).
    /// Carries a diagnostic `detail` string for debugging; not
    /// pattern-matchable on the inner cause.
    #[error("vault data integrity failure: {detail}")]
    CorruptVault {
        /// Diagnostic text from the inner `core::UnlockError` variant's
        /// `Display` impl. Free-form; not part of the API contract.
        detail: String,
    },
}

impl From<FfiUnlockError> for UnlockError {
    fn from(e: FfiUnlockError) -> Self {
        match e {
            FfiUnlockError::WrongPasswordOrCorrupt => Self::WrongPasswordOrCorrupt,
            FfiUnlockError::WrongMnemonicOrCorrupt => Self::WrongMnemonicOrCorrupt,
            FfiUnlockError::InvalidMnemonic { detail } => Self::InvalidMnemonic { detail },
            FfiUnlockError::VaultMismatch => Self::VaultMismatch,
            FfiUnlockError::CorruptVault { detail } => Self::CorruptVault { detail },
        }
    }
}

/// uniffi-side opaque handle. Newtype around bridge's `UnlockedIdentity`;
/// methods are thin forwarders. Drops on foreign refcount → 0 (RAII safety
/// net via uniffi's generated `AutoCloseable.close()` on Kotlin /
/// `deinit` on Swift) or via explicit `wipe()` (preferred — zeroizes
/// the wrapped secrets at exactly the moment of the call).
///
/// The explicit-zeroize method is named `wipe` rather than `close` to
/// avoid colliding with uniffi's auto-generated Kotlin
/// `AutoCloseable.close()`; see `secretary.udl` for the rationale.
pub struct UnlockedIdentity(secretary_ffi_bridge::UnlockedIdentity);

impl UnlockedIdentity {
    /// User-facing display name. Returns `""` if the handle has been wiped.
    pub fn display_name(&self) -> String {
        self.0.display_name()
    }

    /// 16-byte stable identifier. Returns 16 zero bytes if wiped.
    pub fn user_uuid(&self) -> Vec<u8> {
        self.0.user_uuid()
    }

    /// Drop the wrapped identity now, zeroizing all secret fields. Idempotent.
    pub fn wipe(&self) {
        self.0.close();
    }
}

/// uniffi-side opaque-handle wrapper around
/// `secretary_ffi_bridge::MnemonicOutput`. Newtype; methods are thin
/// forwarders.
///
/// One-shot semantics: `take_phrase()` returns `Some(bytes)` once, then
/// `None` on every subsequent call. `wipe()` is idempotent.
///
/// The explicit-zeroize method is named `wipe` rather than `close` for
/// the same reason as `UnlockedIdentity`: uniffi 0.31's Kotlin codegen
/// auto-generates an `AutoCloseable.close()` and a UDL-declared
/// `close()` would collide.
pub struct MnemonicOutput(secretary_ffi_bridge::MnemonicOutput);

impl MnemonicOutput {
    /// Take the recovery phrase as UTF-8 bytes. ONE-SHOT — second call
    /// returns `None`. Bytes are caller-owned heap; caller MUST zeroize
    /// after use.
    pub fn take_phrase(&self) -> Option<Vec<u8>> {
        self.0.take_phrase()
    }

    /// Drop any still-resident inner mnemonic now, zeroizing its
    /// `Sensitive<...>` fields. Idempotent.
    pub fn wipe(&self) {
        self.0.wipe();
    }
}

/// uniffi-side dictionary (struct-by-value) for `create_vault`'s return
/// shape. Two `Vec<u8>` (non-secret) plus two `Arc<Interface>` (uniffi
/// marshals interface-typed dictionary fields as `Arc` handles).
pub struct CreateVaultOutput {
    /// Vault metadata bytes — non-secret. Persist atomically.
    pub vault_toml_bytes: Vec<u8>,
    /// Encrypted identity bundle bytes — non-secret. Persist atomically.
    pub identity_bundle_bytes: Vec<u8>,
    /// Live opaque handle to the just-created identity. Ready for vault
    /// operations immediately; no second `open_with_password` call needed.
    pub identity: std::sync::Arc<UnlockedIdentity>,
    /// One-shot opaque handle for the recovery phrase.
    pub mnemonic: std::sync::Arc<MnemonicOutput>,
}

/// Unlock a vault using its master password. uniffi-projected.
///
/// # Errors
///
/// Returns [`UnlockError`] on failure. See the bridge crate's
/// [`FfiUnlockError`](secretary_ffi_bridge::FfiUnlockError) docs for the
/// thinned 5-variant rationale.
///
/// # Why `Arc<UnlockedIdentity>`?
///
/// uniffi marshals UDL `interface` types as refcounted handles on the
/// foreign side. The Rust signature must therefore return `Arc<T>` (uniffi
/// owns the refcount; the foreign caller's release decrements it). Without
/// the `Arc<>`, uniffi's generated scaffolding emits a type-mismatch error
/// (`expected Result<Arc<UnlockedIdentity>, ...>, found Result<UnlockedIdentity, _>`).
pub fn open_with_password(
    vault_toml_bytes: Vec<u8>,
    identity_bundle_bytes: Vec<u8>,
    mut password: Vec<u8>,
) -> Result<std::sync::Arc<UnlockedIdentity>, UnlockError> {
    // Mirrors the secretary-ffi-py wrapper's stack-residue discipline:
    // zero the password Vec after the bridge returns. The bridge already
    // zeroizes its SecretBytes copy; this wipes the projection-side
    // transient.
    let result = secretary_ffi_bridge::open_with_password(
        &vault_toml_bytes,
        &identity_bundle_bytes,
        &password,
    )
    .map(|inner| std::sync::Arc::new(UnlockedIdentity(inner)))
    .map_err(UnlockError::from);
    password.zeroize();
    result
}

/// Unlock a vault using its 24-word BIP-39 recovery phrase. uniffi-projected.
///
/// Mnemonic input is UTF-8-encoded bytes (`Vec<u8>`); the bridge's UTF-8
/// validation seam surfaces malformed-UTF-8 input as
/// [`UnlockError::InvalidMnemonic`] with `detail: "phrase contained
/// invalid UTF-8"`.
///
/// # Errors
///
/// Returns [`UnlockError`] on failure. See the bridge crate's
/// [`FfiUnlockError`](secretary_ffi_bridge::FfiUnlockError) docs for the
/// thinned 5-variant rationale.
pub fn open_with_recovery(
    vault_toml_bytes: Vec<u8>,
    identity_bundle_bytes: Vec<u8>,
    mut mnemonic: Vec<u8>,
) -> Result<std::sync::Arc<UnlockedIdentity>, UnlockError> {
    // Mirrors the open_with_password wrapper-side stack-residue discipline:
    // zero the mnemonic Vec after the bridge returns. The bridge takes &[u8]
    // and never retains; this Vec is the projection-side transient.
    let result = secretary_ffi_bridge::open_with_recovery(
        &vault_toml_bytes,
        &identity_bundle_bytes,
        &mnemonic,
    )
    .map(|inner| std::sync::Arc::new(UnlockedIdentity(inner)))
    .map_err(UnlockError::from);
    mnemonic.zeroize();
    result
}

/// Create a fresh v1 vault. uniffi-projected. (B.3b)
///
/// The bridge crate instantiates `OsRng` and
/// `Argon2idParams::V1_DEFAULT` internally; foreign callers cannot tune
/// either.
///
/// Returns a [`CreateVaultOutput`] containing on-disk byte artifacts and
/// two opaque handles ([`UnlockedIdentity`] and [`MnemonicOutput`]).
///
/// # Errors
///
/// Returns [`UnlockError`] on failure. See the bridge crate's
/// [`FfiUnlockError`](secretary_ffi_bridge::FfiUnlockError) docs for the
/// thinned 5-variant rationale.
pub fn create_vault(
    mut password: Vec<u8>,
    display_name: String,
    created_at_ms: u64,
) -> Result<CreateVaultOutput, UnlockError> {
    // Mirrors the open_with_password / open_with_recovery wrapper-side
    // stack-residue discipline: zero the password Vec after the bridge
    // returns. The bridge takes &[u8] and never retains; this Vec is the
    // projection-side transient.
    let result = secretary_ffi_bridge::create_vault(&password, &display_name, created_at_ms);
    password.zeroize();

    let bridge_out = result.map_err(UnlockError::from)?;

    let secretary_ffi_bridge::CreateVaultOutput {
        vault_toml_bytes,
        identity_bundle_bytes,
        identity,
        mnemonic,
    } = bridge_out;

    Ok(CreateVaultOutput {
        vault_toml_bytes,
        identity_bundle_bytes,
        identity: std::sync::Arc::new(UnlockedIdentity(identity)),
        mnemonic: std::sync::Arc::new(MnemonicOutput(mnemonic)),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_returns_format_version() {
        assert_eq!(version(), secretary_core::version::FORMAT_VERSION);
    }

    #[test]
    fn add_returns_arithmetic_sum() {
        assert_eq!(add(2, 3), 5);
    }

    #[test]
    fn add_wraps_on_overflow() {
        // Pin the wrapping contract: u32::MAX + 1 wraps to 0. A future
        // change to checked_add / saturating_add (or a switch to a fallible
        // signature in B.2) is a deliberate test failure rather than a
        // silent contract change.
        assert_eq!(add(u32::MAX, 1), 0);
    }

    // -------------------------------------------------------------------
    // B.2: pin the From<FfiUnlockError> for UnlockError mapping.
    //
    // The bridge crate already tests core → FfiUnlockError; these three
    // tests pin the FfiUnlockError → uniffi-side UnlockError translation
    // explicitly so a future variant rename / reorder can't silently
    // remap one variant to another.
    // -------------------------------------------------------------------

    #[test]
    fn from_bridge_wrong_password_or_corrupt_maps_one_to_one() {
        let bridge_err = FfiUnlockError::WrongPasswordOrCorrupt;
        let uniffi_err: UnlockError = bridge_err.into();
        assert!(matches!(uniffi_err, UnlockError::WrongPasswordOrCorrupt));
    }

    #[test]
    fn from_bridge_vault_mismatch_maps_one_to_one() {
        let bridge_err = FfiUnlockError::VaultMismatch;
        let uniffi_err: UnlockError = bridge_err.into();
        assert!(matches!(uniffi_err, UnlockError::VaultMismatch));
    }

    #[test]
    fn from_bridge_corrupt_vault_preserves_detail() {
        // B.3a renamed the bridge's CorruptVault field from `message` to
        // `detail` for naming uniformity with InvalidMnemonic { detail }.
        // Both layers now use `detail`; the From translation is a struct-
        // shorthand pass-through.
        let bridge_err = FfiUnlockError::CorruptVault {
            detail: "fnord".to_string(),
        };
        let uniffi_err: UnlockError = bridge_err.into();
        let UnlockError::CorruptVault { detail } = uniffi_err else {
            panic!("expected CorruptVault");
        };
        assert_eq!(detail, "fnord");
    }

    #[test]
    fn from_bridge_wrong_mnemonic_or_corrupt_maps_one_to_one() {
        let bridge_err = FfiUnlockError::WrongMnemonicOrCorrupt;
        let uniffi_err: UnlockError = bridge_err.into();
        assert!(matches!(uniffi_err, UnlockError::WrongMnemonicOrCorrupt));
    }

    #[test]
    fn from_bridge_invalid_mnemonic_preserves_detail() {
        let bridge_err = FfiUnlockError::InvalidMnemonic {
            detail: "expected 24 words, got 3".to_string(),
        };
        let uniffi_err: UnlockError = bridge_err.into();
        let UnlockError::InvalidMnemonic { detail } = uniffi_err else {
            panic!("expected InvalidMnemonic");
        };
        assert_eq!(detail, "expected 24 words, got 3");
    }

    #[test]
    fn corrupt_vault_display_uses_path_neutral_text() {
        // Mirror of the bridge crate's tripwire (see ffi/secretary-ffi-bridge/
        // src/error.rs). The uniffi-side UnlockError carries its own Display
        // attributes (because uniffi codegen uses this enum to produce the
        // Swift / Kotlin error messages); this test pins the path-neutral
        // wording so a future revert here is a deliberate decision.
        let err = UnlockError::CorruptVault {
            detail: "fnord".to_string(),
        };
        let rendered = format!("{err}");
        assert!(
            rendered.contains("vault data integrity failure"),
            "Display did not contain the path-neutral text: {rendered}",
        );
        assert!(rendered.contains("fnord"), "Display did not include detail");
        assert!(
            !rendered.contains("corrupt or unreadable"),
            "Display still contains the old read-path-only text: {rendered}",
        );
    }

    // -------------------------------------------------------------------
    // B.3b: uniffi-side projection of create_vault.
    //
    // The bridge crate already covers MnemonicOutput contract semantics
    // in isolation (one-shot take_phrase, idempotent wipe, 24-word phrase).
    // The two tests below pin the uniffi-layer wrapper plumbing only:
    // one slow integration test (real Argon2id) and one fast wrapper test
    // (synthesized MnemonicOutput, no Argon2id).
    // -------------------------------------------------------------------

    #[test]
    fn create_vault_returns_live_identity_and_mnemonic() {
        // Slow test: real Argon2id. ~1s. Sole uniffi-layer integration test
        // for create_vault; the bridge crate already covers MnemonicOutput
        // contract semantics in isolation.
        let out = create_vault(
            b"hunter2".to_vec(),
            "UniffiTest".to_string(),
            1_700_000_000_000,
        )
        .expect("create_vault should succeed");
        assert_eq!(out.identity.display_name(), "UniffiTest");
        assert_eq!(out.identity.user_uuid().len(), 16);
        assert!(!out.vault_toml_bytes.is_empty());
        assert!(!out.identity_bundle_bytes.is_empty());

        let phrase = out.mnemonic.take_phrase().expect("phrase available");
        assert_eq!(
            phrase.split(|&b| b == b' ').count(),
            24,
            "expected 24-word phrase",
        );

        let second = out.mnemonic.take_phrase();
        assert!(second.is_none(), "second take_phrase must return None");
    }

    #[test]
    fn mnemonic_output_wipe_is_idempotent_through_uniffi_wrapper() {
        // Fast test: synthesize a MnemonicOutput from a seeded mnemonic
        // generation. No Argon2id; checks the wrapper plumbing only.
        use rand_chacha::{rand_core::SeedableRng, ChaCha20Rng};
        use secretary_core::unlock::mnemonic;
        let mut rng = ChaCha20Rng::from_seed([7u8; 32]);
        let m = mnemonic::generate(&mut rng);
        let bridge_mo = secretary_ffi_bridge::MnemonicOutput::new_for_test(m);
        let mo = MnemonicOutput(bridge_mo);
        mo.wipe();
        mo.wipe(); // must not panic
        assert!(mo.take_phrase().is_none());
    }
}
